// Code generated by ent, DO NOT EDIT.

package realaccount

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the realaccount type in the database.
	Label = "real_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldIdentifier holds the string denoting the identifier field in the database.
	FieldIdentifier = "identifier"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// EdgeUsageSnapshot holds the string denoting the usage_snapshot edge name in mutations.
	EdgeUsageSnapshot = "usage_snapshot"
	// EdgeWebhookBindings holds the string denoting the webhook_bindings edge name in mutations.
	EdgeWebhookBindings = "webhook_bindings"
	// EdgeAlertStates holds the string denoting the alert_states edge name in mutations.
	EdgeAlertStates = "alert_states"
	// Table holds the table name of the realaccount in the database.
	Table = "real_accounts"
	// AccountsTable is the table that holds the accounts relation/edge.
	AccountsTable = "accounts"
	// AccountsInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountsInverseTable = "accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "real_account_id"
	// UsageSnapshotTable is the table that holds the usage_snapshot relation/edge.
	UsageSnapshotTable = "real_account_usage_snapshots"
	// UsageSnapshotInverseTable is the table name for the RealAccountUsageSnapshot entity.
	// It exists in this package in order to avoid circular dependency with the "realaccountusagesnapshot" package.
	UsageSnapshotInverseTable = "real_account_usage_snapshots"
	// UsageSnapshotColumn is the table column denoting the usage_snapshot relation/edge.
	UsageSnapshotColumn = "real_account_id"
	// WebhookBindingsTable is the table that holds the webhook_bindings relation/edge.
	WebhookBindingsTable = "usage_alert_bindings"
	// WebhookBindingsInverseTable is the table name for the UsageAlertBinding entity.
	// It exists in this package in order to avoid circular dependency with the "usagealertbinding" package.
	WebhookBindingsInverseTable = "usage_alert_bindings"
	// WebhookBindingsColumn is the table column denoting the webhook_bindings relation/edge.
	WebhookBindingsColumn = "real_account_id"
	// AlertStatesTable is the table that holds the alert_states relation/edge.
	AlertStatesTable = "usage_alert_states"
	// AlertStatesInverseTable is the table name for the UsageAlertState entity.
	// It exists in this package in order to avoid circular dependency with the "usagealertstate" package.
	AlertStatesInverseTable = "usage_alert_states"
	// AlertStatesColumn is the table column denoting the alert_states relation/edge.
	AlertStatesColumn = "real_account_id"
)

// Columns holds all SQL columns for realaccount fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldPlatform,
	FieldIdentifier,
	FieldNotes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// IdentifierValidator is a validator for the "identifier" field. It is called by the builders before save.
	IdentifierValidator func(string) error
)

// OrderOption defines the ordering options for the RealAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByIdentifier orders the results by the identifier field.
func ByIdentifier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentifier, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByAccountsCount orders the results by accounts count.
func ByAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountsStep(), opts...)
	}
}

// ByAccounts orders the results by accounts terms.
func ByAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUsageSnapshotCount orders the results by usage_snapshot count.
func ByUsageSnapshotCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsageSnapshotStep(), opts...)
	}
}

// ByUsageSnapshot orders the results by usage_snapshot terms.
func ByUsageSnapshot(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageSnapshotStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWebhookBindingsCount orders the results by webhook_bindings count.
func ByWebhookBindingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWebhookBindingsStep(), opts...)
	}
}

// ByWebhookBindings orders the results by webhook_bindings terms.
func ByWebhookBindings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWebhookBindingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAlertStatesCount orders the results by alert_states count.
func ByAlertStatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAlertStatesStep(), opts...)
	}
}

// ByAlertStates orders the results by alert_states terms.
func ByAlertStates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAlertStatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, AccountsTable, AccountsColumn),
	)
}
func newUsageSnapshotStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageSnapshotInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, UsageSnapshotTable, UsageSnapshotColumn),
	)
}
func newWebhookBindingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WebhookBindingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, WebhookBindingsTable, WebhookBindingsColumn),
	)
}
func newAlertStatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AlertStatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, AlertStatesTable, AlertStatesColumn),
	)
}
