// Code generated by ent, DO NOT EDIT.

package usagealertwebhook

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldType, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldURL, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldEnabled, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldRetryCount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldContainsFold(FieldType, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldContainsFold(FieldURL, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNEQ(FieldEnabled, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.FieldLTE(FieldRetryCount, v))
}

// HasBindings applies the HasEdge predicate on the "bindings" edge.
func HasBindings() predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, BindingsTable, BindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBindingsWith applies the HasEdge predicate on the "bindings" edge with a given conditions (other predicates).
func HasBindingsWith(preds ...predicate.UsageAlertBinding) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(func(s *sql.Selector) {
		step := newBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageAlertWebhook) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageAlertWebhook) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageAlertWebhook) predicate.UsageAlertWebhook {
	return predicate.UsageAlertWebhook(sql.NotPredicates(p))
}
