// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/realaccount"
	"github.com/Wei-Shaw/sub2api/ent/realaccountusagesnapshot"
	"github.com/Wei-Shaw/sub2api/ent/usagealertbinding"
	"github.com/Wei-Shaw/sub2api/ent/usagealertrule"
	"github.com/Wei-Shaw/sub2api/ent/usagealertstate"
)

// RealAccountUpdate is the builder for updating RealAccount entities.
type RealAccountUpdate struct {
	config
	hooks    []Hook
	mutation *RealAccountMutation
}

// Where appends a list predicates to the RealAccountUpdate builder.
func (_u *RealAccountUpdate) Where(ps ...predicate.RealAccount) *RealAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RealAccountUpdate) SetUpdatedAt(v time.Time) *RealAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RealAccountUpdate) SetDeletedAt(v time.Time) *RealAccountUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RealAccountUpdate) SetNillableDeletedAt(v *time.Time) *RealAccountUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RealAccountUpdate) ClearDeletedAt() *RealAccountUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *RealAccountUpdate) SetName(v string) *RealAccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RealAccountUpdate) SetNillableName(v *string) *RealAccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *RealAccountUpdate) SetPlatform(v string) *RealAccountUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *RealAccountUpdate) SetNillablePlatform(v *string) *RealAccountUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetIdentifier sets the "identifier" field.
func (_u *RealAccountUpdate) SetIdentifier(v string) *RealAccountUpdate {
	_u.mutation.SetIdentifier(v)
	return _u
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (_u *RealAccountUpdate) SetNillableIdentifier(v *string) *RealAccountUpdate {
	if v != nil {
		_u.SetIdentifier(*v)
	}
	return _u
}

// ClearIdentifier clears the value of the "identifier" field.
func (_u *RealAccountUpdate) ClearIdentifier() *RealAccountUpdate {
	_u.mutation.ClearIdentifier()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RealAccountUpdate) SetNotes(v string) *RealAccountUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RealAccountUpdate) SetNillableNotes(v *string) *RealAccountUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *RealAccountUpdate) ClearNotes() *RealAccountUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *RealAccountUpdate) AddAccountIDs(ids ...int64) *RealAccountUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *RealAccountUpdate) AddAccounts(v ...*Account) *RealAccountUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddUsageSnapshotIDs adds the "usage_snapshot" edge to the RealAccountUsageSnapshot entity by IDs.
func (_u *RealAccountUpdate) AddUsageSnapshotIDs(ids ...int64) *RealAccountUpdate {
	_u.mutation.AddUsageSnapshotIDs(ids...)
	return _u
}

// AddUsageSnapshot adds the "usage_snapshot" edges to the RealAccountUsageSnapshot entity.
func (_u *RealAccountUpdate) AddUsageSnapshot(v ...*RealAccountUsageSnapshot) *RealAccountUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageSnapshotIDs(ids...)
}

// AddWebhookBindingIDs adds the "webhook_bindings" edge to the UsageAlertBinding entity by IDs.
func (_u *RealAccountUpdate) AddWebhookBindingIDs(ids ...int64) *RealAccountUpdate {
	_u.mutation.AddWebhookBindingIDs(ids...)
	return _u
}

// AddWebhookBindings adds the "webhook_bindings" edges to the UsageAlertBinding entity.
func (_u *RealAccountUpdate) AddWebhookBindings(v ...*UsageAlertBinding) *RealAccountUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWebhookBindingIDs(ids...)
}

// AddAlertRuleIDs adds the "alert_rules" edge to the UsageAlertRule entity by IDs.
func (_u *RealAccountUpdate) AddAlertRuleIDs(ids ...int64) *RealAccountUpdate {
	_u.mutation.AddAlertRuleIDs(ids...)
	return _u
}

// AddAlertRules adds the "alert_rules" edges to the UsageAlertRule entity.
func (_u *RealAccountUpdate) AddAlertRules(v ...*UsageAlertRule) *RealAccountUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlertRuleIDs(ids...)
}

// AddAlertStateIDs adds the "alert_states" edge to the UsageAlertState entity by IDs.
func (_u *RealAccountUpdate) AddAlertStateIDs(ids ...int64) *RealAccountUpdate {
	_u.mutation.AddAlertStateIDs(ids...)
	return _u
}

// AddAlertStates adds the "alert_states" edges to the UsageAlertState entity.
func (_u *RealAccountUpdate) AddAlertStates(v ...*UsageAlertState) *RealAccountUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlertStateIDs(ids...)
}

// Mutation returns the RealAccountMutation object of the builder.
func (_u *RealAccountUpdate) Mutation() *RealAccountMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *RealAccountUpdate) ClearAccounts() *RealAccountUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *RealAccountUpdate) RemoveAccountIDs(ids ...int64) *RealAccountUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *RealAccountUpdate) RemoveAccounts(v ...*Account) *RealAccountUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearUsageSnapshot clears all "usage_snapshot" edges to the RealAccountUsageSnapshot entity.
func (_u *RealAccountUpdate) ClearUsageSnapshot() *RealAccountUpdate {
	_u.mutation.ClearUsageSnapshot()
	return _u
}

// RemoveUsageSnapshotIDs removes the "usage_snapshot" edge to RealAccountUsageSnapshot entities by IDs.
func (_u *RealAccountUpdate) RemoveUsageSnapshotIDs(ids ...int64) *RealAccountUpdate {
	_u.mutation.RemoveUsageSnapshotIDs(ids...)
	return _u
}

// RemoveUsageSnapshot removes "usage_snapshot" edges to RealAccountUsageSnapshot entities.
func (_u *RealAccountUpdate) RemoveUsageSnapshot(v ...*RealAccountUsageSnapshot) *RealAccountUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageSnapshotIDs(ids...)
}

// ClearWebhookBindings clears all "webhook_bindings" edges to the UsageAlertBinding entity.
func (_u *RealAccountUpdate) ClearWebhookBindings() *RealAccountUpdate {
	_u.mutation.ClearWebhookBindings()
	return _u
}

// RemoveWebhookBindingIDs removes the "webhook_bindings" edge to UsageAlertBinding entities by IDs.
func (_u *RealAccountUpdate) RemoveWebhookBindingIDs(ids ...int64) *RealAccountUpdate {
	_u.mutation.RemoveWebhookBindingIDs(ids...)
	return _u
}

// RemoveWebhookBindings removes "webhook_bindings" edges to UsageAlertBinding entities.
func (_u *RealAccountUpdate) RemoveWebhookBindings(v ...*UsageAlertBinding) *RealAccountUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWebhookBindingIDs(ids...)
}

// ClearAlertRules clears all "alert_rules" edges to the UsageAlertRule entity.
func (_u *RealAccountUpdate) ClearAlertRules() *RealAccountUpdate {
	_u.mutation.ClearAlertRules()
	return _u
}

// RemoveAlertRuleIDs removes the "alert_rules" edge to UsageAlertRule entities by IDs.
func (_u *RealAccountUpdate) RemoveAlertRuleIDs(ids ...int64) *RealAccountUpdate {
	_u.mutation.RemoveAlertRuleIDs(ids...)
	return _u
}

// RemoveAlertRules removes "alert_rules" edges to UsageAlertRule entities.
func (_u *RealAccountUpdate) RemoveAlertRules(v ...*UsageAlertRule) *RealAccountUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlertRuleIDs(ids...)
}

// ClearAlertStates clears all "alert_states" edges to the UsageAlertState entity.
func (_u *RealAccountUpdate) ClearAlertStates() *RealAccountUpdate {
	_u.mutation.ClearAlertStates()
	return _u
}

// RemoveAlertStateIDs removes the "alert_states" edge to UsageAlertState entities by IDs.
func (_u *RealAccountUpdate) RemoveAlertStateIDs(ids ...int64) *RealAccountUpdate {
	_u.mutation.RemoveAlertStateIDs(ids...)
	return _u
}

// RemoveAlertStates removes "alert_states" edges to UsageAlertState entities.
func (_u *RealAccountUpdate) RemoveAlertStates(v ...*UsageAlertState) *RealAccountUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlertStateIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RealAccountUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RealAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RealAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RealAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RealAccountUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if realaccount.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized realaccount.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := realaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RealAccountUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := realaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RealAccount.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := realaccount.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RealAccount.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Identifier(); ok {
		if err := realaccount.IdentifierValidator(v); err != nil {
			return &ValidationError{Name: "identifier", err: fmt.Errorf(`ent: validator failed for field "RealAccount.identifier": %w`, err)}
		}
	}
	return nil
}

func (_u *RealAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(realaccount.Table, realaccount.Columns, sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(realaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(realaccount.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(realaccount.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(realaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(realaccount.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Identifier(); ok {
		_spec.SetField(realaccount.FieldIdentifier, field.TypeString, value)
	}
	if _u.mutation.IdentifierCleared() {
		_spec.ClearField(realaccount.FieldIdentifier, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(realaccount.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(realaccount.FieldNotes, field.TypeString)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AccountsTable,
			Columns: []string{realaccount.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AccountsTable,
			Columns: []string{realaccount.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AccountsTable,
			Columns: []string{realaccount.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageSnapshotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.UsageSnapshotTable,
			Columns: []string{realaccount.UsageSnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccountusagesnapshot.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageSnapshotIDs(); len(nodes) > 0 && !_u.mutation.UsageSnapshotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.UsageSnapshotTable,
			Columns: []string{realaccount.UsageSnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccountusagesnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageSnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.UsageSnapshotTable,
			Columns: []string{realaccount.UsageSnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccountusagesnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WebhookBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.WebhookBindingsTable,
			Columns: []string{realaccount.WebhookBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWebhookBindingsIDs(); len(nodes) > 0 && !_u.mutation.WebhookBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.WebhookBindingsTable,
			Columns: []string{realaccount.WebhookBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WebhookBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.WebhookBindingsTable,
			Columns: []string{realaccount.WebhookBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlertRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertRulesTable,
			Columns: []string{realaccount.AlertRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlertRulesIDs(); len(nodes) > 0 && !_u.mutation.AlertRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertRulesTable,
			Columns: []string{realaccount.AlertRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertRulesTable,
			Columns: []string{realaccount.AlertRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlertStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertStatesTable,
			Columns: []string{realaccount.AlertStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlertStatesIDs(); len(nodes) > 0 && !_u.mutation.AlertStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertStatesTable,
			Columns: []string{realaccount.AlertStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertStatesTable,
			Columns: []string{realaccount.AlertStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{realaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RealAccountUpdateOne is the builder for updating a single RealAccount entity.
type RealAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RealAccountMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RealAccountUpdateOne) SetUpdatedAt(v time.Time) *RealAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *RealAccountUpdateOne) SetDeletedAt(v time.Time) *RealAccountUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *RealAccountUpdateOne) SetNillableDeletedAt(v *time.Time) *RealAccountUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *RealAccountUpdateOne) ClearDeletedAt() *RealAccountUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *RealAccountUpdateOne) SetName(v string) *RealAccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RealAccountUpdateOne) SetNillableName(v *string) *RealAccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *RealAccountUpdateOne) SetPlatform(v string) *RealAccountUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *RealAccountUpdateOne) SetNillablePlatform(v *string) *RealAccountUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetIdentifier sets the "identifier" field.
func (_u *RealAccountUpdateOne) SetIdentifier(v string) *RealAccountUpdateOne {
	_u.mutation.SetIdentifier(v)
	return _u
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (_u *RealAccountUpdateOne) SetNillableIdentifier(v *string) *RealAccountUpdateOne {
	if v != nil {
		_u.SetIdentifier(*v)
	}
	return _u
}

// ClearIdentifier clears the value of the "identifier" field.
func (_u *RealAccountUpdateOne) ClearIdentifier() *RealAccountUpdateOne {
	_u.mutation.ClearIdentifier()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RealAccountUpdateOne) SetNotes(v string) *RealAccountUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RealAccountUpdateOne) SetNillableNotes(v *string) *RealAccountUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *RealAccountUpdateOne) ClearNotes() *RealAccountUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *RealAccountUpdateOne) AddAccountIDs(ids ...int64) *RealAccountUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *RealAccountUpdateOne) AddAccounts(v ...*Account) *RealAccountUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddUsageSnapshotIDs adds the "usage_snapshot" edge to the RealAccountUsageSnapshot entity by IDs.
func (_u *RealAccountUpdateOne) AddUsageSnapshotIDs(ids ...int64) *RealAccountUpdateOne {
	_u.mutation.AddUsageSnapshotIDs(ids...)
	return _u
}

// AddUsageSnapshot adds the "usage_snapshot" edges to the RealAccountUsageSnapshot entity.
func (_u *RealAccountUpdateOne) AddUsageSnapshot(v ...*RealAccountUsageSnapshot) *RealAccountUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageSnapshotIDs(ids...)
}

// AddWebhookBindingIDs adds the "webhook_bindings" edge to the UsageAlertBinding entity by IDs.
func (_u *RealAccountUpdateOne) AddWebhookBindingIDs(ids ...int64) *RealAccountUpdateOne {
	_u.mutation.AddWebhookBindingIDs(ids...)
	return _u
}

// AddWebhookBindings adds the "webhook_bindings" edges to the UsageAlertBinding entity.
func (_u *RealAccountUpdateOne) AddWebhookBindings(v ...*UsageAlertBinding) *RealAccountUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWebhookBindingIDs(ids...)
}

// AddAlertRuleIDs adds the "alert_rules" edge to the UsageAlertRule entity by IDs.
func (_u *RealAccountUpdateOne) AddAlertRuleIDs(ids ...int64) *RealAccountUpdateOne {
	_u.mutation.AddAlertRuleIDs(ids...)
	return _u
}

// AddAlertRules adds the "alert_rules" edges to the UsageAlertRule entity.
func (_u *RealAccountUpdateOne) AddAlertRules(v ...*UsageAlertRule) *RealAccountUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlertRuleIDs(ids...)
}

// AddAlertStateIDs adds the "alert_states" edge to the UsageAlertState entity by IDs.
func (_u *RealAccountUpdateOne) AddAlertStateIDs(ids ...int64) *RealAccountUpdateOne {
	_u.mutation.AddAlertStateIDs(ids...)
	return _u
}

// AddAlertStates adds the "alert_states" edges to the UsageAlertState entity.
func (_u *RealAccountUpdateOne) AddAlertStates(v ...*UsageAlertState) *RealAccountUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlertStateIDs(ids...)
}

// Mutation returns the RealAccountMutation object of the builder.
func (_u *RealAccountUpdateOne) Mutation() *RealAccountMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *RealAccountUpdateOne) ClearAccounts() *RealAccountUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *RealAccountUpdateOne) RemoveAccountIDs(ids ...int64) *RealAccountUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *RealAccountUpdateOne) RemoveAccounts(v ...*Account) *RealAccountUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearUsageSnapshot clears all "usage_snapshot" edges to the RealAccountUsageSnapshot entity.
func (_u *RealAccountUpdateOne) ClearUsageSnapshot() *RealAccountUpdateOne {
	_u.mutation.ClearUsageSnapshot()
	return _u
}

// RemoveUsageSnapshotIDs removes the "usage_snapshot" edge to RealAccountUsageSnapshot entities by IDs.
func (_u *RealAccountUpdateOne) RemoveUsageSnapshotIDs(ids ...int64) *RealAccountUpdateOne {
	_u.mutation.RemoveUsageSnapshotIDs(ids...)
	return _u
}

// RemoveUsageSnapshot removes "usage_snapshot" edges to RealAccountUsageSnapshot entities.
func (_u *RealAccountUpdateOne) RemoveUsageSnapshot(v ...*RealAccountUsageSnapshot) *RealAccountUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageSnapshotIDs(ids...)
}

// ClearWebhookBindings clears all "webhook_bindings" edges to the UsageAlertBinding entity.
func (_u *RealAccountUpdateOne) ClearWebhookBindings() *RealAccountUpdateOne {
	_u.mutation.ClearWebhookBindings()
	return _u
}

// RemoveWebhookBindingIDs removes the "webhook_bindings" edge to UsageAlertBinding entities by IDs.
func (_u *RealAccountUpdateOne) RemoveWebhookBindingIDs(ids ...int64) *RealAccountUpdateOne {
	_u.mutation.RemoveWebhookBindingIDs(ids...)
	return _u
}

// RemoveWebhookBindings removes "webhook_bindings" edges to UsageAlertBinding entities.
func (_u *RealAccountUpdateOne) RemoveWebhookBindings(v ...*UsageAlertBinding) *RealAccountUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWebhookBindingIDs(ids...)
}

// ClearAlertRules clears all "alert_rules" edges to the UsageAlertRule entity.
func (_u *RealAccountUpdateOne) ClearAlertRules() *RealAccountUpdateOne {
	_u.mutation.ClearAlertRules()
	return _u
}

// RemoveAlertRuleIDs removes the "alert_rules" edge to UsageAlertRule entities by IDs.
func (_u *RealAccountUpdateOne) RemoveAlertRuleIDs(ids ...int64) *RealAccountUpdateOne {
	_u.mutation.RemoveAlertRuleIDs(ids...)
	return _u
}

// RemoveAlertRules removes "alert_rules" edges to UsageAlertRule entities.
func (_u *RealAccountUpdateOne) RemoveAlertRules(v ...*UsageAlertRule) *RealAccountUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlertRuleIDs(ids...)
}

// ClearAlertStates clears all "alert_states" edges to the UsageAlertState entity.
func (_u *RealAccountUpdateOne) ClearAlertStates() *RealAccountUpdateOne {
	_u.mutation.ClearAlertStates()
	return _u
}

// RemoveAlertStateIDs removes the "alert_states" edge to UsageAlertState entities by IDs.
func (_u *RealAccountUpdateOne) RemoveAlertStateIDs(ids ...int64) *RealAccountUpdateOne {
	_u.mutation.RemoveAlertStateIDs(ids...)
	return _u
}

// RemoveAlertStates removes "alert_states" edges to UsageAlertState entities.
func (_u *RealAccountUpdateOne) RemoveAlertStates(v ...*UsageAlertState) *RealAccountUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlertStateIDs(ids...)
}

// Where appends a list predicates to the RealAccountUpdate builder.
func (_u *RealAccountUpdateOne) Where(ps ...predicate.RealAccount) *RealAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RealAccountUpdateOne) Select(field string, fields ...string) *RealAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RealAccount entity.
func (_u *RealAccountUpdateOne) Save(ctx context.Context) (*RealAccount, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RealAccountUpdateOne) SaveX(ctx context.Context) *RealAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RealAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RealAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RealAccountUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if realaccount.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized realaccount.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := realaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *RealAccountUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := realaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RealAccount.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := realaccount.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RealAccount.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Identifier(); ok {
		if err := realaccount.IdentifierValidator(v); err != nil {
			return &ValidationError{Name: "identifier", err: fmt.Errorf(`ent: validator failed for field "RealAccount.identifier": %w`, err)}
		}
	}
	return nil
}

func (_u *RealAccountUpdateOne) sqlSave(ctx context.Context) (_node *RealAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(realaccount.Table, realaccount.Columns, sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RealAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, realaccount.FieldID)
		for _, f := range fields {
			if !realaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != realaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(realaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(realaccount.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(realaccount.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(realaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(realaccount.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.Identifier(); ok {
		_spec.SetField(realaccount.FieldIdentifier, field.TypeString, value)
	}
	if _u.mutation.IdentifierCleared() {
		_spec.ClearField(realaccount.FieldIdentifier, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(realaccount.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(realaccount.FieldNotes, field.TypeString)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AccountsTable,
			Columns: []string{realaccount.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AccountsTable,
			Columns: []string{realaccount.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AccountsTable,
			Columns: []string{realaccount.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageSnapshotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.UsageSnapshotTable,
			Columns: []string{realaccount.UsageSnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccountusagesnapshot.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageSnapshotIDs(); len(nodes) > 0 && !_u.mutation.UsageSnapshotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.UsageSnapshotTable,
			Columns: []string{realaccount.UsageSnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccountusagesnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageSnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.UsageSnapshotTable,
			Columns: []string{realaccount.UsageSnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccountusagesnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WebhookBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.WebhookBindingsTable,
			Columns: []string{realaccount.WebhookBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWebhookBindingsIDs(); len(nodes) > 0 && !_u.mutation.WebhookBindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.WebhookBindingsTable,
			Columns: []string{realaccount.WebhookBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WebhookBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.WebhookBindingsTable,
			Columns: []string{realaccount.WebhookBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlertRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertRulesTable,
			Columns: []string{realaccount.AlertRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlertRulesIDs(); len(nodes) > 0 && !_u.mutation.AlertRulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertRulesTable,
			Columns: []string{realaccount.AlertRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertRulesTable,
			Columns: []string{realaccount.AlertRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AlertStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertStatesTable,
			Columns: []string{realaccount.AlertStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlertStatesIDs(); len(nodes) > 0 && !_u.mutation.AlertStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertStatesTable,
			Columns: []string{realaccount.AlertStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlertStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertStatesTable,
			Columns: []string{realaccount.AlertStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RealAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{realaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
