// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/realaccount"
	"github.com/Wei-Shaw/sub2api/ent/realaccountusagesnapshot"
)

// RealAccountUsageSnapshotCreate is the builder for creating a RealAccountUsageSnapshot entity.
type RealAccountUsageSnapshotCreate struct {
	config
	mutation *RealAccountUsageSnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RealAccountUsageSnapshotCreate) SetCreatedAt(v time.Time) *RealAccountUsageSnapshotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RealAccountUsageSnapshotCreate) SetNillableCreatedAt(v *time.Time) *RealAccountUsageSnapshotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RealAccountUsageSnapshotCreate) SetUpdatedAt(v time.Time) *RealAccountUsageSnapshotCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RealAccountUsageSnapshotCreate) SetNillableUpdatedAt(v *time.Time) *RealAccountUsageSnapshotCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRealAccountID sets the "real_account_id" field.
func (_c *RealAccountUsageSnapshotCreate) SetRealAccountID(v int64) *RealAccountUsageSnapshotCreate {
	_c.mutation.SetRealAccountID(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *RealAccountUsageSnapshotCreate) SetPlatform(v string) *RealAccountUsageSnapshotCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *RealAccountUsageSnapshotCreate) SetSource(v string) *RealAccountUsageSnapshotCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetSnapshotJSON sets the "snapshot_json" field.
func (_c *RealAccountUsageSnapshotCreate) SetSnapshotJSON(v map[string]interface{}) *RealAccountUsageSnapshotCreate {
	_c.mutation.SetSnapshotJSON(v)
	return _c
}

// SetSampledAt sets the "sampled_at" field.
func (_c *RealAccountUsageSnapshotCreate) SetSampledAt(v time.Time) *RealAccountUsageSnapshotCreate {
	_c.mutation.SetSampledAt(v)
	return _c
}

// SetRealAccount sets the "real_account" edge to the RealAccount entity.
func (_c *RealAccountUsageSnapshotCreate) SetRealAccount(v *RealAccount) *RealAccountUsageSnapshotCreate {
	return _c.SetRealAccountID(v.ID)
}

// Mutation returns the RealAccountUsageSnapshotMutation object of the builder.
func (_c *RealAccountUsageSnapshotCreate) Mutation() *RealAccountUsageSnapshotMutation {
	return _c.mutation
}

// Save creates the RealAccountUsageSnapshot in the database.
func (_c *RealAccountUsageSnapshotCreate) Save(ctx context.Context) (*RealAccountUsageSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RealAccountUsageSnapshotCreate) SaveX(ctx context.Context) *RealAccountUsageSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RealAccountUsageSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RealAccountUsageSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RealAccountUsageSnapshotCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := realaccountusagesnapshot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := realaccountusagesnapshot.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SnapshotJSON(); !ok {
		v := realaccountusagesnapshot.DefaultSnapshotJSON()
		_c.mutation.SetSnapshotJSON(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RealAccountUsageSnapshotCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RealAccountUsageSnapshot.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RealAccountUsageSnapshot.updated_at"`)}
	}
	if _, ok := _c.mutation.RealAccountID(); !ok {
		return &ValidationError{Name: "real_account_id", err: errors.New(`ent: missing required field "RealAccountUsageSnapshot.real_account_id"`)}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "RealAccountUsageSnapshot.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := realaccountusagesnapshot.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RealAccountUsageSnapshot.platform": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "RealAccountUsageSnapshot.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := realaccountusagesnapshot.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "RealAccountUsageSnapshot.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SnapshotJSON(); !ok {
		return &ValidationError{Name: "snapshot_json", err: errors.New(`ent: missing required field "RealAccountUsageSnapshot.snapshot_json"`)}
	}
	if _, ok := _c.mutation.SampledAt(); !ok {
		return &ValidationError{Name: "sampled_at", err: errors.New(`ent: missing required field "RealAccountUsageSnapshot.sampled_at"`)}
	}
	if len(_c.mutation.RealAccountIDs()) == 0 {
		return &ValidationError{Name: "real_account", err: errors.New(`ent: missing required edge "RealAccountUsageSnapshot.real_account"`)}
	}
	return nil
}

func (_c *RealAccountUsageSnapshotCreate) sqlSave(ctx context.Context) (*RealAccountUsageSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RealAccountUsageSnapshotCreate) createSpec() (*RealAccountUsageSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &RealAccountUsageSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(realaccountusagesnapshot.Table, sqlgraph.NewFieldSpec(realaccountusagesnapshot.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(realaccountusagesnapshot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(realaccountusagesnapshot.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(realaccountusagesnapshot.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(realaccountusagesnapshot.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SnapshotJSON(); ok {
		_spec.SetField(realaccountusagesnapshot.FieldSnapshotJSON, field.TypeJSON, value)
		_node.SnapshotJSON = value
	}
	if value, ok := _c.mutation.SampledAt(); ok {
		_spec.SetField(realaccountusagesnapshot.FieldSampledAt, field.TypeTime, value)
		_node.SampledAt = value
	}
	if nodes := _c.mutation.RealAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   realaccountusagesnapshot.RealAccountTable,
			Columns: []string{realaccountusagesnapshot.RealAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RealAccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RealAccountUsageSnapshot.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RealAccountUsageSnapshotUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RealAccountUsageSnapshotCreate) OnConflict(opts ...sql.ConflictOption) *RealAccountUsageSnapshotUpsertOne {
	_c.conflict = opts
	return &RealAccountUsageSnapshotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RealAccountUsageSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RealAccountUsageSnapshotCreate) OnConflictColumns(columns ...string) *RealAccountUsageSnapshotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RealAccountUsageSnapshotUpsertOne{
		create: _c,
	}
}

type (
	// RealAccountUsageSnapshotUpsertOne is the builder for "upsert"-ing
	//  one RealAccountUsageSnapshot node.
	RealAccountUsageSnapshotUpsertOne struct {
		create *RealAccountUsageSnapshotCreate
	}

	// RealAccountUsageSnapshotUpsert is the "OnConflict" setter.
	RealAccountUsageSnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RealAccountUsageSnapshotUpsert) SetUpdatedAt(v time.Time) *RealAccountUsageSnapshotUpsert {
	u.Set(realaccountusagesnapshot.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsert) UpdateUpdatedAt() *RealAccountUsageSnapshotUpsert {
	u.SetExcluded(realaccountusagesnapshot.FieldUpdatedAt)
	return u
}

// SetRealAccountID sets the "real_account_id" field.
func (u *RealAccountUsageSnapshotUpsert) SetRealAccountID(v int64) *RealAccountUsageSnapshotUpsert {
	u.Set(realaccountusagesnapshot.FieldRealAccountID, v)
	return u
}

// UpdateRealAccountID sets the "real_account_id" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsert) UpdateRealAccountID() *RealAccountUsageSnapshotUpsert {
	u.SetExcluded(realaccountusagesnapshot.FieldRealAccountID)
	return u
}

// SetPlatform sets the "platform" field.
func (u *RealAccountUsageSnapshotUpsert) SetPlatform(v string) *RealAccountUsageSnapshotUpsert {
	u.Set(realaccountusagesnapshot.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsert) UpdatePlatform() *RealAccountUsageSnapshotUpsert {
	u.SetExcluded(realaccountusagesnapshot.FieldPlatform)
	return u
}

// SetSource sets the "source" field.
func (u *RealAccountUsageSnapshotUpsert) SetSource(v string) *RealAccountUsageSnapshotUpsert {
	u.Set(realaccountusagesnapshot.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsert) UpdateSource() *RealAccountUsageSnapshotUpsert {
	u.SetExcluded(realaccountusagesnapshot.FieldSource)
	return u
}

// SetSnapshotJSON sets the "snapshot_json" field.
func (u *RealAccountUsageSnapshotUpsert) SetSnapshotJSON(v map[string]interface{}) *RealAccountUsageSnapshotUpsert {
	u.Set(realaccountusagesnapshot.FieldSnapshotJSON, v)
	return u
}

// UpdateSnapshotJSON sets the "snapshot_json" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsert) UpdateSnapshotJSON() *RealAccountUsageSnapshotUpsert {
	u.SetExcluded(realaccountusagesnapshot.FieldSnapshotJSON)
	return u
}

// SetSampledAt sets the "sampled_at" field.
func (u *RealAccountUsageSnapshotUpsert) SetSampledAt(v time.Time) *RealAccountUsageSnapshotUpsert {
	u.Set(realaccountusagesnapshot.FieldSampledAt, v)
	return u
}

// UpdateSampledAt sets the "sampled_at" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsert) UpdateSampledAt() *RealAccountUsageSnapshotUpsert {
	u.SetExcluded(realaccountusagesnapshot.FieldSampledAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RealAccountUsageSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RealAccountUsageSnapshotUpsertOne) UpdateNewValues() *RealAccountUsageSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(realaccountusagesnapshot.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RealAccountUsageSnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RealAccountUsageSnapshotUpsertOne) Ignore() *RealAccountUsageSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RealAccountUsageSnapshotUpsertOne) DoNothing() *RealAccountUsageSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RealAccountUsageSnapshotCreate.OnConflict
// documentation for more info.
func (u *RealAccountUsageSnapshotUpsertOne) Update(set func(*RealAccountUsageSnapshotUpsert)) *RealAccountUsageSnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RealAccountUsageSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RealAccountUsageSnapshotUpsertOne) SetUpdatedAt(v time.Time) *RealAccountUsageSnapshotUpsertOne {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsertOne) UpdateUpdatedAt() *RealAccountUsageSnapshotUpsertOne {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRealAccountID sets the "real_account_id" field.
func (u *RealAccountUsageSnapshotUpsertOne) SetRealAccountID(v int64) *RealAccountUsageSnapshotUpsertOne {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.SetRealAccountID(v)
	})
}

// UpdateRealAccountID sets the "real_account_id" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsertOne) UpdateRealAccountID() *RealAccountUsageSnapshotUpsertOne {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.UpdateRealAccountID()
	})
}

// SetPlatform sets the "platform" field.
func (u *RealAccountUsageSnapshotUpsertOne) SetPlatform(v string) *RealAccountUsageSnapshotUpsertOne {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsertOne) UpdatePlatform() *RealAccountUsageSnapshotUpsertOne {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.UpdatePlatform()
	})
}

// SetSource sets the "source" field.
func (u *RealAccountUsageSnapshotUpsertOne) SetSource(v string) *RealAccountUsageSnapshotUpsertOne {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsertOne) UpdateSource() *RealAccountUsageSnapshotUpsertOne {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.UpdateSource()
	})
}

// SetSnapshotJSON sets the "snapshot_json" field.
func (u *RealAccountUsageSnapshotUpsertOne) SetSnapshotJSON(v map[string]interface{}) *RealAccountUsageSnapshotUpsertOne {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.SetSnapshotJSON(v)
	})
}

// UpdateSnapshotJSON sets the "snapshot_json" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsertOne) UpdateSnapshotJSON() *RealAccountUsageSnapshotUpsertOne {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.UpdateSnapshotJSON()
	})
}

// SetSampledAt sets the "sampled_at" field.
func (u *RealAccountUsageSnapshotUpsertOne) SetSampledAt(v time.Time) *RealAccountUsageSnapshotUpsertOne {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.SetSampledAt(v)
	})
}

// UpdateSampledAt sets the "sampled_at" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsertOne) UpdateSampledAt() *RealAccountUsageSnapshotUpsertOne {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.UpdateSampledAt()
	})
}

// Exec executes the query.
func (u *RealAccountUsageSnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RealAccountUsageSnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RealAccountUsageSnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RealAccountUsageSnapshotUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RealAccountUsageSnapshotUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RealAccountUsageSnapshotCreateBulk is the builder for creating many RealAccountUsageSnapshot entities in bulk.
type RealAccountUsageSnapshotCreateBulk struct {
	config
	err      error
	builders []*RealAccountUsageSnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the RealAccountUsageSnapshot entities in the database.
func (_c *RealAccountUsageSnapshotCreateBulk) Save(ctx context.Context) ([]*RealAccountUsageSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RealAccountUsageSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RealAccountUsageSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RealAccountUsageSnapshotCreateBulk) SaveX(ctx context.Context) []*RealAccountUsageSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RealAccountUsageSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RealAccountUsageSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RealAccountUsageSnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RealAccountUsageSnapshotUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RealAccountUsageSnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *RealAccountUsageSnapshotUpsertBulk {
	_c.conflict = opts
	return &RealAccountUsageSnapshotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RealAccountUsageSnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RealAccountUsageSnapshotCreateBulk) OnConflictColumns(columns ...string) *RealAccountUsageSnapshotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RealAccountUsageSnapshotUpsertBulk{
		create: _c,
	}
}

// RealAccountUsageSnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of RealAccountUsageSnapshot nodes.
type RealAccountUsageSnapshotUpsertBulk struct {
	create *RealAccountUsageSnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RealAccountUsageSnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RealAccountUsageSnapshotUpsertBulk) UpdateNewValues() *RealAccountUsageSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(realaccountusagesnapshot.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RealAccountUsageSnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RealAccountUsageSnapshotUpsertBulk) Ignore() *RealAccountUsageSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RealAccountUsageSnapshotUpsertBulk) DoNothing() *RealAccountUsageSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RealAccountUsageSnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *RealAccountUsageSnapshotUpsertBulk) Update(set func(*RealAccountUsageSnapshotUpsert)) *RealAccountUsageSnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RealAccountUsageSnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RealAccountUsageSnapshotUpsertBulk) SetUpdatedAt(v time.Time) *RealAccountUsageSnapshotUpsertBulk {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsertBulk) UpdateUpdatedAt() *RealAccountUsageSnapshotUpsertBulk {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRealAccountID sets the "real_account_id" field.
func (u *RealAccountUsageSnapshotUpsertBulk) SetRealAccountID(v int64) *RealAccountUsageSnapshotUpsertBulk {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.SetRealAccountID(v)
	})
}

// UpdateRealAccountID sets the "real_account_id" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsertBulk) UpdateRealAccountID() *RealAccountUsageSnapshotUpsertBulk {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.UpdateRealAccountID()
	})
}

// SetPlatform sets the "platform" field.
func (u *RealAccountUsageSnapshotUpsertBulk) SetPlatform(v string) *RealAccountUsageSnapshotUpsertBulk {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsertBulk) UpdatePlatform() *RealAccountUsageSnapshotUpsertBulk {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.UpdatePlatform()
	})
}

// SetSource sets the "source" field.
func (u *RealAccountUsageSnapshotUpsertBulk) SetSource(v string) *RealAccountUsageSnapshotUpsertBulk {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsertBulk) UpdateSource() *RealAccountUsageSnapshotUpsertBulk {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.UpdateSource()
	})
}

// SetSnapshotJSON sets the "snapshot_json" field.
func (u *RealAccountUsageSnapshotUpsertBulk) SetSnapshotJSON(v map[string]interface{}) *RealAccountUsageSnapshotUpsertBulk {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.SetSnapshotJSON(v)
	})
}

// UpdateSnapshotJSON sets the "snapshot_json" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsertBulk) UpdateSnapshotJSON() *RealAccountUsageSnapshotUpsertBulk {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.UpdateSnapshotJSON()
	})
}

// SetSampledAt sets the "sampled_at" field.
func (u *RealAccountUsageSnapshotUpsertBulk) SetSampledAt(v time.Time) *RealAccountUsageSnapshotUpsertBulk {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.SetSampledAt(v)
	})
}

// UpdateSampledAt sets the "sampled_at" field to the value that was provided on create.
func (u *RealAccountUsageSnapshotUpsertBulk) UpdateSampledAt() *RealAccountUsageSnapshotUpsertBulk {
	return u.Update(func(s *RealAccountUsageSnapshotUpsert) {
		s.UpdateSampledAt()
	})
}

// Exec executes the query.
func (u *RealAccountUsageSnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RealAccountUsageSnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RealAccountUsageSnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RealAccountUsageSnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
