// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/realaccount"
	"github.com/Wei-Shaw/sub2api/ent/realaccountusagesnapshot"
	"github.com/Wei-Shaw/sub2api/ent/usagealertbinding"
	"github.com/Wei-Shaw/sub2api/ent/usagealertrule"
	"github.com/Wei-Shaw/sub2api/ent/usagealertstate"
)

// RealAccountCreate is the builder for creating a RealAccount entity.
type RealAccountCreate struct {
	config
	mutation *RealAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RealAccountCreate) SetCreatedAt(v time.Time) *RealAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RealAccountCreate) SetNillableCreatedAt(v *time.Time) *RealAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RealAccountCreate) SetUpdatedAt(v time.Time) *RealAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RealAccountCreate) SetNillableUpdatedAt(v *time.Time) *RealAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *RealAccountCreate) SetDeletedAt(v time.Time) *RealAccountCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *RealAccountCreate) SetNillableDeletedAt(v *time.Time) *RealAccountCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *RealAccountCreate) SetName(v string) *RealAccountCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPlatform sets the "platform" field.
func (_c *RealAccountCreate) SetPlatform(v string) *RealAccountCreate {
	_c.mutation.SetPlatform(v)
	return _c
}

// SetIdentifier sets the "identifier" field.
func (_c *RealAccountCreate) SetIdentifier(v string) *RealAccountCreate {
	_c.mutation.SetIdentifier(v)
	return _c
}

// SetNillableIdentifier sets the "identifier" field if the given value is not nil.
func (_c *RealAccountCreate) SetNillableIdentifier(v *string) *RealAccountCreate {
	if v != nil {
		_c.SetIdentifier(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *RealAccountCreate) SetNotes(v string) *RealAccountCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *RealAccountCreate) SetNillableNotes(v *string) *RealAccountCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *RealAccountCreate) AddAccountIDs(ids ...int64) *RealAccountCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *RealAccountCreate) AddAccounts(v ...*Account) *RealAccountCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// AddUsageSnapshotIDs adds the "usage_snapshot" edge to the RealAccountUsageSnapshot entity by IDs.
func (_c *RealAccountCreate) AddUsageSnapshotIDs(ids ...int64) *RealAccountCreate {
	_c.mutation.AddUsageSnapshotIDs(ids...)
	return _c
}

// AddUsageSnapshot adds the "usage_snapshot" edges to the RealAccountUsageSnapshot entity.
func (_c *RealAccountCreate) AddUsageSnapshot(v ...*RealAccountUsageSnapshot) *RealAccountCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageSnapshotIDs(ids...)
}

// AddWebhookBindingIDs adds the "webhook_bindings" edge to the UsageAlertBinding entity by IDs.
func (_c *RealAccountCreate) AddWebhookBindingIDs(ids ...int64) *RealAccountCreate {
	_c.mutation.AddWebhookBindingIDs(ids...)
	return _c
}

// AddWebhookBindings adds the "webhook_bindings" edges to the UsageAlertBinding entity.
func (_c *RealAccountCreate) AddWebhookBindings(v ...*UsageAlertBinding) *RealAccountCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWebhookBindingIDs(ids...)
}

// AddAlertRuleIDs adds the "alert_rules" edge to the UsageAlertRule entity by IDs.
func (_c *RealAccountCreate) AddAlertRuleIDs(ids ...int64) *RealAccountCreate {
	_c.mutation.AddAlertRuleIDs(ids...)
	return _c
}

// AddAlertRules adds the "alert_rules" edges to the UsageAlertRule entity.
func (_c *RealAccountCreate) AddAlertRules(v ...*UsageAlertRule) *RealAccountCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAlertRuleIDs(ids...)
}

// AddAlertStateIDs adds the "alert_states" edge to the UsageAlertState entity by IDs.
func (_c *RealAccountCreate) AddAlertStateIDs(ids ...int64) *RealAccountCreate {
	_c.mutation.AddAlertStateIDs(ids...)
	return _c
}

// AddAlertStates adds the "alert_states" edges to the UsageAlertState entity.
func (_c *RealAccountCreate) AddAlertStates(v ...*UsageAlertState) *RealAccountCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAlertStateIDs(ids...)
}

// Mutation returns the RealAccountMutation object of the builder.
func (_c *RealAccountCreate) Mutation() *RealAccountMutation {
	return _c.mutation
}

// Save creates the RealAccount in the database.
func (_c *RealAccountCreate) Save(ctx context.Context) (*RealAccount, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RealAccountCreate) SaveX(ctx context.Context) *RealAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RealAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RealAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RealAccountCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if realaccount.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized realaccount.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := realaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if realaccount.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized realaccount.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := realaccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *RealAccountCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RealAccount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RealAccount.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RealAccount.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := realaccount.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RealAccount.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "RealAccount.platform"`)}
	}
	if v, ok := _c.mutation.Platform(); ok {
		if err := realaccount.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "RealAccount.platform": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Identifier(); ok {
		if err := realaccount.IdentifierValidator(v); err != nil {
			return &ValidationError{Name: "identifier", err: fmt.Errorf(`ent: validator failed for field "RealAccount.identifier": %w`, err)}
		}
	}
	return nil
}

func (_c *RealAccountCreate) sqlSave(ctx context.Context) (*RealAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RealAccountCreate) createSpec() (*RealAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &RealAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(realaccount.Table, sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(realaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(realaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(realaccount.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(realaccount.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Platform(); ok {
		_spec.SetField(realaccount.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := _c.mutation.Identifier(); ok {
		_spec.SetField(realaccount.FieldIdentifier, field.TypeString, value)
		_node.Identifier = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(realaccount.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AccountsTable,
			Columns: []string{realaccount.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageSnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.UsageSnapshotTable,
			Columns: []string{realaccount.UsageSnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccountusagesnapshot.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WebhookBindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.WebhookBindingsTable,
			Columns: []string{realaccount.WebhookBindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AlertRulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertRulesTable,
			Columns: []string{realaccount.AlertRulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AlertStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   realaccount.AlertStatesTable,
			Columns: []string{realaccount.AlertStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RealAccount.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RealAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RealAccountCreate) OnConflict(opts ...sql.ConflictOption) *RealAccountUpsertOne {
	_c.conflict = opts
	return &RealAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RealAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RealAccountCreate) OnConflictColumns(columns ...string) *RealAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RealAccountUpsertOne{
		create: _c,
	}
}

type (
	// RealAccountUpsertOne is the builder for "upsert"-ing
	//  one RealAccount node.
	RealAccountUpsertOne struct {
		create *RealAccountCreate
	}

	// RealAccountUpsert is the "OnConflict" setter.
	RealAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RealAccountUpsert) SetUpdatedAt(v time.Time) *RealAccountUpsert {
	u.Set(realaccount.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RealAccountUpsert) UpdateUpdatedAt() *RealAccountUpsert {
	u.SetExcluded(realaccount.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RealAccountUpsert) SetDeletedAt(v time.Time) *RealAccountUpsert {
	u.Set(realaccount.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RealAccountUpsert) UpdateDeletedAt() *RealAccountUpsert {
	u.SetExcluded(realaccount.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RealAccountUpsert) ClearDeletedAt() *RealAccountUpsert {
	u.SetNull(realaccount.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *RealAccountUpsert) SetName(v string) *RealAccountUpsert {
	u.Set(realaccount.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RealAccountUpsert) UpdateName() *RealAccountUpsert {
	u.SetExcluded(realaccount.FieldName)
	return u
}

// SetPlatform sets the "platform" field.
func (u *RealAccountUpsert) SetPlatform(v string) *RealAccountUpsert {
	u.Set(realaccount.FieldPlatform, v)
	return u
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RealAccountUpsert) UpdatePlatform() *RealAccountUpsert {
	u.SetExcluded(realaccount.FieldPlatform)
	return u
}

// SetIdentifier sets the "identifier" field.
func (u *RealAccountUpsert) SetIdentifier(v string) *RealAccountUpsert {
	u.Set(realaccount.FieldIdentifier, v)
	return u
}

// UpdateIdentifier sets the "identifier" field to the value that was provided on create.
func (u *RealAccountUpsert) UpdateIdentifier() *RealAccountUpsert {
	u.SetExcluded(realaccount.FieldIdentifier)
	return u
}

// ClearIdentifier clears the value of the "identifier" field.
func (u *RealAccountUpsert) ClearIdentifier() *RealAccountUpsert {
	u.SetNull(realaccount.FieldIdentifier)
	return u
}

// SetNotes sets the "notes" field.
func (u *RealAccountUpsert) SetNotes(v string) *RealAccountUpsert {
	u.Set(realaccount.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RealAccountUpsert) UpdateNotes() *RealAccountUpsert {
	u.SetExcluded(realaccount.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *RealAccountUpsert) ClearNotes() *RealAccountUpsert {
	u.SetNull(realaccount.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RealAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RealAccountUpsertOne) UpdateNewValues() *RealAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(realaccount.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RealAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RealAccountUpsertOne) Ignore() *RealAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RealAccountUpsertOne) DoNothing() *RealAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RealAccountCreate.OnConflict
// documentation for more info.
func (u *RealAccountUpsertOne) Update(set func(*RealAccountUpsert)) *RealAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RealAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RealAccountUpsertOne) SetUpdatedAt(v time.Time) *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RealAccountUpsertOne) UpdateUpdatedAt() *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RealAccountUpsertOne) SetDeletedAt(v time.Time) *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RealAccountUpsertOne) UpdateDeletedAt() *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RealAccountUpsertOne) ClearDeletedAt() *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *RealAccountUpsertOne) SetName(v string) *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RealAccountUpsertOne) UpdateName() *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *RealAccountUpsertOne) SetPlatform(v string) *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RealAccountUpsertOne) UpdatePlatform() *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.UpdatePlatform()
	})
}

// SetIdentifier sets the "identifier" field.
func (u *RealAccountUpsertOne) SetIdentifier(v string) *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.SetIdentifier(v)
	})
}

// UpdateIdentifier sets the "identifier" field to the value that was provided on create.
func (u *RealAccountUpsertOne) UpdateIdentifier() *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.UpdateIdentifier()
	})
}

// ClearIdentifier clears the value of the "identifier" field.
func (u *RealAccountUpsertOne) ClearIdentifier() *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.ClearIdentifier()
	})
}

// SetNotes sets the "notes" field.
func (u *RealAccountUpsertOne) SetNotes(v string) *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RealAccountUpsertOne) UpdateNotes() *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *RealAccountUpsertOne) ClearNotes() *RealAccountUpsertOne {
	return u.Update(func(s *RealAccountUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *RealAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RealAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RealAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RealAccountUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RealAccountUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RealAccountCreateBulk is the builder for creating many RealAccount entities in bulk.
type RealAccountCreateBulk struct {
	config
	err      error
	builders []*RealAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the RealAccount entities in the database.
func (_c *RealAccountCreateBulk) Save(ctx context.Context) ([]*RealAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RealAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RealAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RealAccountCreateBulk) SaveX(ctx context.Context) []*RealAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RealAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RealAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RealAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RealAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RealAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *RealAccountUpsertBulk {
	_c.conflict = opts
	return &RealAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RealAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RealAccountCreateBulk) OnConflictColumns(columns ...string) *RealAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RealAccountUpsertBulk{
		create: _c,
	}
}

// RealAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of RealAccount nodes.
type RealAccountUpsertBulk struct {
	create *RealAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RealAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RealAccountUpsertBulk) UpdateNewValues() *RealAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(realaccount.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RealAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RealAccountUpsertBulk) Ignore() *RealAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RealAccountUpsertBulk) DoNothing() *RealAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RealAccountCreateBulk.OnConflict
// documentation for more info.
func (u *RealAccountUpsertBulk) Update(set func(*RealAccountUpsert)) *RealAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RealAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RealAccountUpsertBulk) SetUpdatedAt(v time.Time) *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RealAccountUpsertBulk) UpdateUpdatedAt() *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *RealAccountUpsertBulk) SetDeletedAt(v time.Time) *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *RealAccountUpsertBulk) UpdateDeletedAt() *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *RealAccountUpsertBulk) ClearDeletedAt() *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *RealAccountUpsertBulk) SetName(v string) *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RealAccountUpsertBulk) UpdateName() *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.UpdateName()
	})
}

// SetPlatform sets the "platform" field.
func (u *RealAccountUpsertBulk) SetPlatform(v string) *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.SetPlatform(v)
	})
}

// UpdatePlatform sets the "platform" field to the value that was provided on create.
func (u *RealAccountUpsertBulk) UpdatePlatform() *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.UpdatePlatform()
	})
}

// SetIdentifier sets the "identifier" field.
func (u *RealAccountUpsertBulk) SetIdentifier(v string) *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.SetIdentifier(v)
	})
}

// UpdateIdentifier sets the "identifier" field to the value that was provided on create.
func (u *RealAccountUpsertBulk) UpdateIdentifier() *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.UpdateIdentifier()
	})
}

// ClearIdentifier clears the value of the "identifier" field.
func (u *RealAccountUpsertBulk) ClearIdentifier() *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.ClearIdentifier()
	})
}

// SetNotes sets the "notes" field.
func (u *RealAccountUpsertBulk) SetNotes(v string) *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RealAccountUpsertBulk) UpdateNotes() *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *RealAccountUpsertBulk) ClearNotes() *RealAccountUpsertBulk {
	return u.Update(func(s *RealAccountUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *RealAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RealAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RealAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RealAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
