// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/realaccount"
	"github.com/Wei-Shaw/sub2api/ent/realaccountusagesnapshot"
	"github.com/Wei-Shaw/sub2api/ent/usagealertbinding"
	"github.com/Wei-Shaw/sub2api/ent/usagealertrule"
	"github.com/Wei-Shaw/sub2api/ent/usagealertstate"
)

// RealAccountQuery is the builder for querying RealAccount entities.
type RealAccountQuery struct {
	config
	ctx                 *QueryContext
	order               []realaccount.OrderOption
	inters              []Interceptor
	predicates          []predicate.RealAccount
	withAccounts        *AccountQuery
	withUsageSnapshot   *RealAccountUsageSnapshotQuery
	withWebhookBindings *UsageAlertBindingQuery
	withAlertRules      *UsageAlertRuleQuery
	withAlertStates     *UsageAlertStateQuery
	modifiers           []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RealAccountQuery builder.
func (_q *RealAccountQuery) Where(ps ...predicate.RealAccount) *RealAccountQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RealAccountQuery) Limit(limit int) *RealAccountQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RealAccountQuery) Offset(offset int) *RealAccountQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RealAccountQuery) Unique(unique bool) *RealAccountQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RealAccountQuery) Order(o ...realaccount.OrderOption) *RealAccountQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryAccounts chains the current query on the "accounts" edge.
func (_q *RealAccountQuery) QueryAccounts() *AccountQuery {
	query := (&AccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(realaccount.Table, realaccount.FieldID, selector),
			sqlgraph.To(account.Table, account.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, realaccount.AccountsTable, realaccount.AccountsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsageSnapshot chains the current query on the "usage_snapshot" edge.
func (_q *RealAccountQuery) QueryUsageSnapshot() *RealAccountUsageSnapshotQuery {
	query := (&RealAccountUsageSnapshotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(realaccount.Table, realaccount.FieldID, selector),
			sqlgraph.To(realaccountusagesnapshot.Table, realaccountusagesnapshot.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, realaccount.UsageSnapshotTable, realaccount.UsageSnapshotColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWebhookBindings chains the current query on the "webhook_bindings" edge.
func (_q *RealAccountQuery) QueryWebhookBindings() *UsageAlertBindingQuery {
	query := (&UsageAlertBindingClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(realaccount.Table, realaccount.FieldID, selector),
			sqlgraph.To(usagealertbinding.Table, usagealertbinding.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, realaccount.WebhookBindingsTable, realaccount.WebhookBindingsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAlertRules chains the current query on the "alert_rules" edge.
func (_q *RealAccountQuery) QueryAlertRules() *UsageAlertRuleQuery {
	query := (&UsageAlertRuleClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(realaccount.Table, realaccount.FieldID, selector),
			sqlgraph.To(usagealertrule.Table, usagealertrule.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, realaccount.AlertRulesTable, realaccount.AlertRulesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAlertStates chains the current query on the "alert_states" edge.
func (_q *RealAccountQuery) QueryAlertStates() *UsageAlertStateQuery {
	query := (&UsageAlertStateClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(realaccount.Table, realaccount.FieldID, selector),
			sqlgraph.To(usagealertstate.Table, usagealertstate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, realaccount.AlertStatesTable, realaccount.AlertStatesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RealAccount entity from the query.
// Returns a *NotFoundError when no RealAccount was found.
func (_q *RealAccountQuery) First(ctx context.Context) (*RealAccount, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{realaccount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RealAccountQuery) FirstX(ctx context.Context) *RealAccount {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RealAccount ID from the query.
// Returns a *NotFoundError when no RealAccount ID was found.
func (_q *RealAccountQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{realaccount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RealAccountQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RealAccount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RealAccount entity is found.
// Returns a *NotFoundError when no RealAccount entities are found.
func (_q *RealAccountQuery) Only(ctx context.Context) (*RealAccount, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{realaccount.Label}
	default:
		return nil, &NotSingularError{realaccount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RealAccountQuery) OnlyX(ctx context.Context) *RealAccount {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RealAccount ID in the query.
// Returns a *NotSingularError when more than one RealAccount ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RealAccountQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{realaccount.Label}
	default:
		err = &NotSingularError{realaccount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RealAccountQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RealAccounts.
func (_q *RealAccountQuery) All(ctx context.Context) ([]*RealAccount, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RealAccount, *RealAccountQuery]()
	return withInterceptors[[]*RealAccount](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RealAccountQuery) AllX(ctx context.Context) []*RealAccount {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RealAccount IDs.
func (_q *RealAccountQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(realaccount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RealAccountQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RealAccountQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RealAccountQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RealAccountQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RealAccountQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RealAccountQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RealAccountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RealAccountQuery) Clone() *RealAccountQuery {
	if _q == nil {
		return nil
	}
	return &RealAccountQuery{
		config:              _q.config,
		ctx:                 _q.ctx.Clone(),
		order:               append([]realaccount.OrderOption{}, _q.order...),
		inters:              append([]Interceptor{}, _q.inters...),
		predicates:          append([]predicate.RealAccount{}, _q.predicates...),
		withAccounts:        _q.withAccounts.Clone(),
		withUsageSnapshot:   _q.withUsageSnapshot.Clone(),
		withWebhookBindings: _q.withWebhookBindings.Clone(),
		withAlertRules:      _q.withAlertRules.Clone(),
		withAlertStates:     _q.withAlertStates.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithAccounts tells the query-builder to eager-load the nodes that are connected to
// the "accounts" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RealAccountQuery) WithAccounts(opts ...func(*AccountQuery)) *RealAccountQuery {
	query := (&AccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAccounts = query
	return _q
}

// WithUsageSnapshot tells the query-builder to eager-load the nodes that are connected to
// the "usage_snapshot" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RealAccountQuery) WithUsageSnapshot(opts ...func(*RealAccountUsageSnapshotQuery)) *RealAccountQuery {
	query := (&RealAccountUsageSnapshotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUsageSnapshot = query
	return _q
}

// WithWebhookBindings tells the query-builder to eager-load the nodes that are connected to
// the "webhook_bindings" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RealAccountQuery) WithWebhookBindings(opts ...func(*UsageAlertBindingQuery)) *RealAccountQuery {
	query := (&UsageAlertBindingClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWebhookBindings = query
	return _q
}

// WithAlertRules tells the query-builder to eager-load the nodes that are connected to
// the "alert_rules" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RealAccountQuery) WithAlertRules(opts ...func(*UsageAlertRuleQuery)) *RealAccountQuery {
	query := (&UsageAlertRuleClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAlertRules = query
	return _q
}

// WithAlertStates tells the query-builder to eager-load the nodes that are connected to
// the "alert_states" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RealAccountQuery) WithAlertStates(opts ...func(*UsageAlertStateQuery)) *RealAccountQuery {
	query := (&UsageAlertStateClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAlertStates = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RealAccount.Query().
//		GroupBy(realaccount.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RealAccountQuery) GroupBy(field string, fields ...string) *RealAccountGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RealAccountGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = realaccount.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.RealAccount.Query().
//		Select(realaccount.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *RealAccountQuery) Select(fields ...string) *RealAccountSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RealAccountSelect{RealAccountQuery: _q}
	sbuild.label = realaccount.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RealAccountSelect configured with the given aggregations.
func (_q *RealAccountQuery) Aggregate(fns ...AggregateFunc) *RealAccountSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RealAccountQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !realaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RealAccountQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RealAccount, error) {
	var (
		nodes       = []*RealAccount{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withAccounts != nil,
			_q.withUsageSnapshot != nil,
			_q.withWebhookBindings != nil,
			_q.withAlertRules != nil,
			_q.withAlertStates != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RealAccount).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RealAccount{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withAccounts; query != nil {
		if err := _q.loadAccounts(ctx, query, nodes,
			func(n *RealAccount) { n.Edges.Accounts = []*Account{} },
			func(n *RealAccount, e *Account) { n.Edges.Accounts = append(n.Edges.Accounts, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUsageSnapshot; query != nil {
		if err := _q.loadUsageSnapshot(ctx, query, nodes,
			func(n *RealAccount) { n.Edges.UsageSnapshot = []*RealAccountUsageSnapshot{} },
			func(n *RealAccount, e *RealAccountUsageSnapshot) {
				n.Edges.UsageSnapshot = append(n.Edges.UsageSnapshot, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withWebhookBindings; query != nil {
		if err := _q.loadWebhookBindings(ctx, query, nodes,
			func(n *RealAccount) { n.Edges.WebhookBindings = []*UsageAlertBinding{} },
			func(n *RealAccount, e *UsageAlertBinding) {
				n.Edges.WebhookBindings = append(n.Edges.WebhookBindings, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withAlertRules; query != nil {
		if err := _q.loadAlertRules(ctx, query, nodes,
			func(n *RealAccount) { n.Edges.AlertRules = []*UsageAlertRule{} },
			func(n *RealAccount, e *UsageAlertRule) { n.Edges.AlertRules = append(n.Edges.AlertRules, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAlertStates; query != nil {
		if err := _q.loadAlertStates(ctx, query, nodes,
			func(n *RealAccount) { n.Edges.AlertStates = []*UsageAlertState{} },
			func(n *RealAccount, e *UsageAlertState) { n.Edges.AlertStates = append(n.Edges.AlertStates, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RealAccountQuery) loadAccounts(ctx context.Context, query *AccountQuery, nodes []*RealAccount, init func(*RealAccount), assign func(*RealAccount, *Account)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RealAccount)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(account.FieldRealAccountID)
	}
	query.Where(predicate.Account(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(realaccount.AccountsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RealAccountID
		if fk == nil {
			return fmt.Errorf(`foreign-key "real_account_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "real_account_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RealAccountQuery) loadUsageSnapshot(ctx context.Context, query *RealAccountUsageSnapshotQuery, nodes []*RealAccount, init func(*RealAccount), assign func(*RealAccount, *RealAccountUsageSnapshot)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RealAccount)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(realaccountusagesnapshot.FieldRealAccountID)
	}
	query.Where(predicate.RealAccountUsageSnapshot(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(realaccount.UsageSnapshotColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RealAccountID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "real_account_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RealAccountQuery) loadWebhookBindings(ctx context.Context, query *UsageAlertBindingQuery, nodes []*RealAccount, init func(*RealAccount), assign func(*RealAccount, *UsageAlertBinding)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RealAccount)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(usagealertbinding.FieldRealAccountID)
	}
	query.Where(predicate.UsageAlertBinding(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(realaccount.WebhookBindingsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RealAccountID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "real_account_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RealAccountQuery) loadAlertRules(ctx context.Context, query *UsageAlertRuleQuery, nodes []*RealAccount, init func(*RealAccount), assign func(*RealAccount, *UsageAlertRule)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RealAccount)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(usagealertrule.FieldRealAccountID)
	}
	query.Where(predicate.UsageAlertRule(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(realaccount.AlertRulesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RealAccountID
		if fk == nil {
			return fmt.Errorf(`foreign-key "real_account_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "real_account_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *RealAccountQuery) loadAlertStates(ctx context.Context, query *UsageAlertStateQuery, nodes []*RealAccount, init func(*RealAccount), assign func(*RealAccount, *UsageAlertState)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*RealAccount)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(usagealertstate.FieldRealAccountID)
	}
	query.Where(predicate.UsageAlertState(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(realaccount.AlertStatesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RealAccountID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "real_account_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *RealAccountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RealAccountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(realaccount.Table, realaccount.Columns, sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, realaccount.FieldID)
		for i := range fields {
			if fields[i] != realaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RealAccountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(realaccount.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = realaccount.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *RealAccountQuery) ForUpdate(opts ...sql.LockOption) *RealAccountQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *RealAccountQuery) ForShare(opts ...sql.LockOption) *RealAccountQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// RealAccountGroupBy is the group-by builder for RealAccount entities.
type RealAccountGroupBy struct {
	selector
	build *RealAccountQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RealAccountGroupBy) Aggregate(fns ...AggregateFunc) *RealAccountGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RealAccountGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RealAccountQuery, *RealAccountGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RealAccountGroupBy) sqlScan(ctx context.Context, root *RealAccountQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RealAccountSelect is the builder for selecting fields of RealAccount entities.
type RealAccountSelect struct {
	*RealAccountQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RealAccountSelect) Aggregate(fns ...AggregateFunc) *RealAccountSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RealAccountSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RealAccountQuery, *RealAccountSelect](ctx, _s.RealAccountQuery, _s, _s.inters, v)
}

func (_s *RealAccountSelect) sqlScan(ctx context.Context, root *RealAccountQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
