// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/realaccount"
	"github.com/Wei-Shaw/sub2api/ent/realaccountusagesnapshot"
)

// RealAccountUsageSnapshot is the model entity for the RealAccountUsageSnapshot schema.
type RealAccountUsageSnapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RealAccountID holds the value of the "real_account_id" field.
	RealAccountID int64 `json:"real_account_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// SnapshotJSON holds the value of the "snapshot_json" field.
	SnapshotJSON map[string]interface{} `json:"snapshot_json,omitempty"`
	// SampledAt holds the value of the "sampled_at" field.
	SampledAt time.Time `json:"sampled_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RealAccountUsageSnapshotQuery when eager-loading is set.
	Edges        RealAccountUsageSnapshotEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RealAccountUsageSnapshotEdges holds the relations/edges for other nodes in the graph.
type RealAccountUsageSnapshotEdges struct {
	// RealAccount holds the value of the real_account edge.
	RealAccount *RealAccount `json:"real_account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RealAccountOrErr returns the RealAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RealAccountUsageSnapshotEdges) RealAccountOrErr() (*RealAccount, error) {
	if e.RealAccount != nil {
		return e.RealAccount, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: realaccount.Label}
	}
	return nil, &NotLoadedError{edge: "real_account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RealAccountUsageSnapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case realaccountusagesnapshot.FieldSnapshotJSON:
			values[i] = new([]byte)
		case realaccountusagesnapshot.FieldID, realaccountusagesnapshot.FieldRealAccountID:
			values[i] = new(sql.NullInt64)
		case realaccountusagesnapshot.FieldPlatform, realaccountusagesnapshot.FieldSource:
			values[i] = new(sql.NullString)
		case realaccountusagesnapshot.FieldCreatedAt, realaccountusagesnapshot.FieldUpdatedAt, realaccountusagesnapshot.FieldSampledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RealAccountUsageSnapshot fields.
func (_m *RealAccountUsageSnapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case realaccountusagesnapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case realaccountusagesnapshot.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case realaccountusagesnapshot.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case realaccountusagesnapshot.FieldRealAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field real_account_id", values[i])
			} else if value.Valid {
				_m.RealAccountID = value.Int64
			}
		case realaccountusagesnapshot.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case realaccountusagesnapshot.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case realaccountusagesnapshot.FieldSnapshotJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field snapshot_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SnapshotJSON); err != nil {
					return fmt.Errorf("unmarshal field snapshot_json: %w", err)
				}
			}
		case realaccountusagesnapshot.FieldSampledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sampled_at", values[i])
			} else if value.Valid {
				_m.SampledAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RealAccountUsageSnapshot.
// This includes values selected through modifiers, order, etc.
func (_m *RealAccountUsageSnapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRealAccount queries the "real_account" edge of the RealAccountUsageSnapshot entity.
func (_m *RealAccountUsageSnapshot) QueryRealAccount() *RealAccountQuery {
	return NewRealAccountUsageSnapshotClient(_m.config).QueryRealAccount(_m)
}

// Update returns a builder for updating this RealAccountUsageSnapshot.
// Note that you need to call RealAccountUsageSnapshot.Unwrap() before calling this method if this RealAccountUsageSnapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RealAccountUsageSnapshot) Update() *RealAccountUsageSnapshotUpdateOne {
	return NewRealAccountUsageSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RealAccountUsageSnapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RealAccountUsageSnapshot) Unwrap() *RealAccountUsageSnapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RealAccountUsageSnapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RealAccountUsageSnapshot) String() string {
	var builder strings.Builder
	builder.WriteString("RealAccountUsageSnapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("real_account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RealAccountID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("snapshot_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.SnapshotJSON))
	builder.WriteString(", ")
	builder.WriteString("sampled_at=")
	builder.WriteString(_m.SampledAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RealAccountUsageSnapshots is a parsable slice of RealAccountUsageSnapshot.
type RealAccountUsageSnapshots []*RealAccountUsageSnapshot
