// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/realaccount"
	"github.com/Wei-Shaw/sub2api/ent/usagealertbinding"
	"github.com/Wei-Shaw/sub2api/ent/usagealertwebhook"
)

// UsageAlertBindingCreate is the builder for creating a UsageAlertBinding entity.
type UsageAlertBindingCreate struct {
	config
	mutation *UsageAlertBindingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageAlertBindingCreate) SetCreatedAt(v time.Time) *UsageAlertBindingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageAlertBindingCreate) SetNillableCreatedAt(v *time.Time) *UsageAlertBindingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UsageAlertBindingCreate) SetUpdatedAt(v time.Time) *UsageAlertBindingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UsageAlertBindingCreate) SetNillableUpdatedAt(v *time.Time) *UsageAlertBindingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRealAccountID sets the "real_account_id" field.
func (_c *UsageAlertBindingCreate) SetRealAccountID(v int64) *UsageAlertBindingCreate {
	_c.mutation.SetRealAccountID(v)
	return _c
}

// SetWebhookID sets the "webhook_id" field.
func (_c *UsageAlertBindingCreate) SetWebhookID(v int64) *UsageAlertBindingCreate {
	_c.mutation.SetWebhookID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *UsageAlertBindingCreate) SetEnabled(v bool) *UsageAlertBindingCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *UsageAlertBindingCreate) SetNillableEnabled(v *bool) *UsageAlertBindingCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRealAccount sets the "real_account" edge to the RealAccount entity.
func (_c *UsageAlertBindingCreate) SetRealAccount(v *RealAccount) *UsageAlertBindingCreate {
	return _c.SetRealAccountID(v.ID)
}

// SetWebhook sets the "webhook" edge to the UsageAlertWebhook entity.
func (_c *UsageAlertBindingCreate) SetWebhook(v *UsageAlertWebhook) *UsageAlertBindingCreate {
	return _c.SetWebhookID(v.ID)
}

// Mutation returns the UsageAlertBindingMutation object of the builder.
func (_c *UsageAlertBindingCreate) Mutation() *UsageAlertBindingMutation {
	return _c.mutation
}

// Save creates the UsageAlertBinding in the database.
func (_c *UsageAlertBindingCreate) Save(ctx context.Context) (*UsageAlertBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageAlertBindingCreate) SaveX(ctx context.Context) *UsageAlertBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageAlertBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageAlertBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageAlertBindingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagealertbinding.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usagealertbinding.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := usagealertbinding.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageAlertBindingCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageAlertBinding.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UsageAlertBinding.updated_at"`)}
	}
	if _, ok := _c.mutation.RealAccountID(); !ok {
		return &ValidationError{Name: "real_account_id", err: errors.New(`ent: missing required field "UsageAlertBinding.real_account_id"`)}
	}
	if _, ok := _c.mutation.WebhookID(); !ok {
		return &ValidationError{Name: "webhook_id", err: errors.New(`ent: missing required field "UsageAlertBinding.webhook_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "UsageAlertBinding.enabled"`)}
	}
	if len(_c.mutation.RealAccountIDs()) == 0 {
		return &ValidationError{Name: "real_account", err: errors.New(`ent: missing required edge "UsageAlertBinding.real_account"`)}
	}
	if len(_c.mutation.WebhookIDs()) == 0 {
		return &ValidationError{Name: "webhook", err: errors.New(`ent: missing required edge "UsageAlertBinding.webhook"`)}
	}
	return nil
}

func (_c *UsageAlertBindingCreate) sqlSave(ctx context.Context) (*UsageAlertBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageAlertBindingCreate) createSpec() (*UsageAlertBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageAlertBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagealertbinding.Table, sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagealertbinding.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usagealertbinding.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(usagealertbinding.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if nodes := _c.mutation.RealAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertbinding.RealAccountTable,
			Columns: []string{usagealertbinding.RealAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RealAccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WebhookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertbinding.WebhookTable,
			Columns: []string{usagealertbinding.WebhookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertwebhook.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WebhookID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageAlertBinding.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageAlertBindingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageAlertBindingCreate) OnConflict(opts ...sql.ConflictOption) *UsageAlertBindingUpsertOne {
	_c.conflict = opts
	return &UsageAlertBindingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageAlertBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageAlertBindingCreate) OnConflictColumns(columns ...string) *UsageAlertBindingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageAlertBindingUpsertOne{
		create: _c,
	}
}

type (
	// UsageAlertBindingUpsertOne is the builder for "upsert"-ing
	//  one UsageAlertBinding node.
	UsageAlertBindingUpsertOne struct {
		create *UsageAlertBindingCreate
	}

	// UsageAlertBindingUpsert is the "OnConflict" setter.
	UsageAlertBindingUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageAlertBindingUpsert) SetUpdatedAt(v time.Time) *UsageAlertBindingUpsert {
	u.Set(usagealertbinding.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageAlertBindingUpsert) UpdateUpdatedAt() *UsageAlertBindingUpsert {
	u.SetExcluded(usagealertbinding.FieldUpdatedAt)
	return u
}

// SetRealAccountID sets the "real_account_id" field.
func (u *UsageAlertBindingUpsert) SetRealAccountID(v int64) *UsageAlertBindingUpsert {
	u.Set(usagealertbinding.FieldRealAccountID, v)
	return u
}

// UpdateRealAccountID sets the "real_account_id" field to the value that was provided on create.
func (u *UsageAlertBindingUpsert) UpdateRealAccountID() *UsageAlertBindingUpsert {
	u.SetExcluded(usagealertbinding.FieldRealAccountID)
	return u
}

// SetWebhookID sets the "webhook_id" field.
func (u *UsageAlertBindingUpsert) SetWebhookID(v int64) *UsageAlertBindingUpsert {
	u.Set(usagealertbinding.FieldWebhookID, v)
	return u
}

// UpdateWebhookID sets the "webhook_id" field to the value that was provided on create.
func (u *UsageAlertBindingUpsert) UpdateWebhookID() *UsageAlertBindingUpsert {
	u.SetExcluded(usagealertbinding.FieldWebhookID)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *UsageAlertBindingUpsert) SetEnabled(v bool) *UsageAlertBindingUpsert {
	u.Set(usagealertbinding.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UsageAlertBindingUpsert) UpdateEnabled() *UsageAlertBindingUpsert {
	u.SetExcluded(usagealertbinding.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UsageAlertBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageAlertBindingUpsertOne) UpdateNewValues() *UsageAlertBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usagealertbinding.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageAlertBinding.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageAlertBindingUpsertOne) Ignore() *UsageAlertBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageAlertBindingUpsertOne) DoNothing() *UsageAlertBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageAlertBindingCreate.OnConflict
// documentation for more info.
func (u *UsageAlertBindingUpsertOne) Update(set func(*UsageAlertBindingUpsert)) *UsageAlertBindingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageAlertBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageAlertBindingUpsertOne) SetUpdatedAt(v time.Time) *UsageAlertBindingUpsertOne {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageAlertBindingUpsertOne) UpdateUpdatedAt() *UsageAlertBindingUpsertOne {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRealAccountID sets the "real_account_id" field.
func (u *UsageAlertBindingUpsertOne) SetRealAccountID(v int64) *UsageAlertBindingUpsertOne {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.SetRealAccountID(v)
	})
}

// UpdateRealAccountID sets the "real_account_id" field to the value that was provided on create.
func (u *UsageAlertBindingUpsertOne) UpdateRealAccountID() *UsageAlertBindingUpsertOne {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.UpdateRealAccountID()
	})
}

// SetWebhookID sets the "webhook_id" field.
func (u *UsageAlertBindingUpsertOne) SetWebhookID(v int64) *UsageAlertBindingUpsertOne {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.SetWebhookID(v)
	})
}

// UpdateWebhookID sets the "webhook_id" field to the value that was provided on create.
func (u *UsageAlertBindingUpsertOne) UpdateWebhookID() *UsageAlertBindingUpsertOne {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.UpdateWebhookID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UsageAlertBindingUpsertOne) SetEnabled(v bool) *UsageAlertBindingUpsertOne {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UsageAlertBindingUpsertOne) UpdateEnabled() *UsageAlertBindingUpsertOne {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *UsageAlertBindingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageAlertBindingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageAlertBindingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageAlertBindingUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageAlertBindingUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageAlertBindingCreateBulk is the builder for creating many UsageAlertBinding entities in bulk.
type UsageAlertBindingCreateBulk struct {
	config
	err      error
	builders []*UsageAlertBindingCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageAlertBinding entities in the database.
func (_c *UsageAlertBindingCreateBulk) Save(ctx context.Context) ([]*UsageAlertBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageAlertBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageAlertBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageAlertBindingCreateBulk) SaveX(ctx context.Context) []*UsageAlertBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageAlertBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageAlertBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageAlertBinding.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageAlertBindingUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageAlertBindingCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageAlertBindingUpsertBulk {
	_c.conflict = opts
	return &UsageAlertBindingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageAlertBinding.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageAlertBindingCreateBulk) OnConflictColumns(columns ...string) *UsageAlertBindingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageAlertBindingUpsertBulk{
		create: _c,
	}
}

// UsageAlertBindingUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageAlertBinding nodes.
type UsageAlertBindingUpsertBulk struct {
	create *UsageAlertBindingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageAlertBinding.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageAlertBindingUpsertBulk) UpdateNewValues() *UsageAlertBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usagealertbinding.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageAlertBinding.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageAlertBindingUpsertBulk) Ignore() *UsageAlertBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageAlertBindingUpsertBulk) DoNothing() *UsageAlertBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageAlertBindingCreateBulk.OnConflict
// documentation for more info.
func (u *UsageAlertBindingUpsertBulk) Update(set func(*UsageAlertBindingUpsert)) *UsageAlertBindingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageAlertBindingUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageAlertBindingUpsertBulk) SetUpdatedAt(v time.Time) *UsageAlertBindingUpsertBulk {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageAlertBindingUpsertBulk) UpdateUpdatedAt() *UsageAlertBindingUpsertBulk {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRealAccountID sets the "real_account_id" field.
func (u *UsageAlertBindingUpsertBulk) SetRealAccountID(v int64) *UsageAlertBindingUpsertBulk {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.SetRealAccountID(v)
	})
}

// UpdateRealAccountID sets the "real_account_id" field to the value that was provided on create.
func (u *UsageAlertBindingUpsertBulk) UpdateRealAccountID() *UsageAlertBindingUpsertBulk {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.UpdateRealAccountID()
	})
}

// SetWebhookID sets the "webhook_id" field.
func (u *UsageAlertBindingUpsertBulk) SetWebhookID(v int64) *UsageAlertBindingUpsertBulk {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.SetWebhookID(v)
	})
}

// UpdateWebhookID sets the "webhook_id" field to the value that was provided on create.
func (u *UsageAlertBindingUpsertBulk) UpdateWebhookID() *UsageAlertBindingUpsertBulk {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.UpdateWebhookID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UsageAlertBindingUpsertBulk) SetEnabled(v bool) *UsageAlertBindingUpsertBulk {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UsageAlertBindingUpsertBulk) UpdateEnabled() *UsageAlertBindingUpsertBulk {
	return u.Update(func(s *UsageAlertBindingUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *UsageAlertBindingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageAlertBindingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageAlertBindingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageAlertBindingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
