// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/realaccount"
	"github.com/Wei-Shaw/sub2api/ent/usagealertrule"
)

// UsageAlertRule is the model entity for the UsageAlertRule schema.
type UsageAlertRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// RealAccountID holds the value of the "real_account_id" field.
	RealAccountID *int64 `json:"real_account_id,omitempty"`
	// Window holds the value of the "window" field.
	Window string `json:"window,omitempty"`
	// Metric holds the value of the "metric" field.
	Metric string `json:"metric,omitempty"`
	// Operator holds the value of the "operator" field.
	Operator string `json:"operator,omitempty"`
	// Threshold holds the value of the "threshold" field.
	Threshold float64 `json:"threshold,omitempty"`
	// MinResetAfterHours holds the value of the "min_reset_after_hours" field.
	MinResetAfterHours *float64 `json:"min_reset_after_hours,omitempty"`
	// StepPercent holds the value of the "step_percent" field.
	StepPercent *float64 `json:"step_percent,omitempty"`
	// CooldownMinutes holds the value of the "cooldown_minutes" field.
	CooldownMinutes int `json:"cooldown_minutes,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageAlertRuleQuery when eager-loading is set.
	Edges        UsageAlertRuleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsageAlertRuleEdges holds the relations/edges for other nodes in the graph.
type UsageAlertRuleEdges struct {
	// RealAccount holds the value of the real_account edge.
	RealAccount *RealAccount `json:"real_account,omitempty"`
	// States holds the value of the states edge.
	States []*UsageAlertState `json:"states,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RealAccountOrErr returns the RealAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageAlertRuleEdges) RealAccountOrErr() (*RealAccount, error) {
	if e.RealAccount != nil {
		return e.RealAccount, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: realaccount.Label}
	}
	return nil, &NotLoadedError{edge: "real_account"}
}

// StatesOrErr returns the States value or an error if the edge
// was not loaded in eager-loading.
func (e UsageAlertRuleEdges) StatesOrErr() ([]*UsageAlertState, error) {
	if e.loadedTypes[1] {
		return e.States, nil
	}
	return nil, &NotLoadedError{edge: "states"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageAlertRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagealertrule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case usagealertrule.FieldThreshold, usagealertrule.FieldMinResetAfterHours, usagealertrule.FieldStepPercent:
			values[i] = new(sql.NullFloat64)
		case usagealertrule.FieldID, usagealertrule.FieldRealAccountID, usagealertrule.FieldCooldownMinutes:
			values[i] = new(sql.NullInt64)
		case usagealertrule.FieldName, usagealertrule.FieldPlatform, usagealertrule.FieldWindow, usagealertrule.FieldMetric, usagealertrule.FieldOperator:
			values[i] = new(sql.NullString)
		case usagealertrule.FieldCreatedAt, usagealertrule.FieldUpdatedAt, usagealertrule.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageAlertRule fields.
func (_m *UsageAlertRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagealertrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usagealertrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usagealertrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usagealertrule.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case usagealertrule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case usagealertrule.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = value.String
			}
		case usagealertrule.FieldRealAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field real_account_id", values[i])
			} else if value.Valid {
				_m.RealAccountID = new(int64)
				*_m.RealAccountID = value.Int64
			}
		case usagealertrule.FieldWindow:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field window", values[i])
			} else if value.Valid {
				_m.Window = value.String
			}
		case usagealertrule.FieldMetric:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metric", values[i])
			} else if value.Valid {
				_m.Metric = value.String
			}
		case usagealertrule.FieldOperator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field operator", values[i])
			} else if value.Valid {
				_m.Operator = value.String
			}
		case usagealertrule.FieldThreshold:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field threshold", values[i])
			} else if value.Valid {
				_m.Threshold = value.Float64
			}
		case usagealertrule.FieldMinResetAfterHours:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field min_reset_after_hours", values[i])
			} else if value.Valid {
				_m.MinResetAfterHours = new(float64)
				*_m.MinResetAfterHours = value.Float64
			}
		case usagealertrule.FieldStepPercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field step_percent", values[i])
			} else if value.Valid {
				_m.StepPercent = new(float64)
				*_m.StepPercent = value.Float64
			}
		case usagealertrule.FieldCooldownMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cooldown_minutes", values[i])
			} else if value.Valid {
				_m.CooldownMinutes = int(value.Int64)
			}
		case usagealertrule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageAlertRule.
// This includes values selected through modifiers, order, etc.
func (_m *UsageAlertRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRealAccount queries the "real_account" edge of the UsageAlertRule entity.
func (_m *UsageAlertRule) QueryRealAccount() *RealAccountQuery {
	return NewUsageAlertRuleClient(_m.config).QueryRealAccount(_m)
}

// QueryStates queries the "states" edge of the UsageAlertRule entity.
func (_m *UsageAlertRule) QueryStates() *UsageAlertStateQuery {
	return NewUsageAlertRuleClient(_m.config).QueryStates(_m)
}

// Update returns a builder for updating this UsageAlertRule.
// Note that you need to call UsageAlertRule.Unwrap() before calling this method if this UsageAlertRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageAlertRule) Update() *UsageAlertRuleUpdateOne {
	return NewUsageAlertRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageAlertRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageAlertRule) Unwrap() *UsageAlertRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageAlertRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageAlertRule) String() string {
	var builder strings.Builder
	builder.WriteString("UsageAlertRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(_m.Platform)
	builder.WriteString(", ")
	if v := _m.RealAccountID; v != nil {
		builder.WriteString("real_account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("window=")
	builder.WriteString(_m.Window)
	builder.WriteString(", ")
	builder.WriteString("metric=")
	builder.WriteString(_m.Metric)
	builder.WriteString(", ")
	builder.WriteString("operator=")
	builder.WriteString(_m.Operator)
	builder.WriteString(", ")
	builder.WriteString("threshold=")
	builder.WriteString(fmt.Sprintf("%v", _m.Threshold))
	builder.WriteString(", ")
	if v := _m.MinResetAfterHours; v != nil {
		builder.WriteString("min_reset_after_hours=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.StepPercent; v != nil {
		builder.WriteString("step_percent=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("cooldown_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.CooldownMinutes))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// UsageAlertRules is a parsable slice of UsageAlertRule.
type UsageAlertRules []*UsageAlertRule
