// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/realaccount"
	"github.com/Wei-Shaw/sub2api/ent/usagealertbinding"
	"github.com/Wei-Shaw/sub2api/ent/usagealertwebhook"
)

// UsageAlertBinding is the model entity for the UsageAlertBinding schema.
type UsageAlertBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RealAccountID holds the value of the "real_account_id" field.
	RealAccountID int64 `json:"real_account_id,omitempty"`
	// WebhookID holds the value of the "webhook_id" field.
	WebhookID int64 `json:"webhook_id,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageAlertBindingQuery when eager-loading is set.
	Edges        UsageAlertBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsageAlertBindingEdges holds the relations/edges for other nodes in the graph.
type UsageAlertBindingEdges struct {
	// RealAccount holds the value of the real_account edge.
	RealAccount *RealAccount `json:"real_account,omitempty"`
	// Webhook holds the value of the webhook edge.
	Webhook *UsageAlertWebhook `json:"webhook,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RealAccountOrErr returns the RealAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageAlertBindingEdges) RealAccountOrErr() (*RealAccount, error) {
	if e.RealAccount != nil {
		return e.RealAccount, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: realaccount.Label}
	}
	return nil, &NotLoadedError{edge: "real_account"}
}

// WebhookOrErr returns the Webhook value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageAlertBindingEdges) WebhookOrErr() (*UsageAlertWebhook, error) {
	if e.Webhook != nil {
		return e.Webhook, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: usagealertwebhook.Label}
	}
	return nil, &NotLoadedError{edge: "webhook"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageAlertBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagealertbinding.FieldEnabled:
			values[i] = new(sql.NullBool)
		case usagealertbinding.FieldID, usagealertbinding.FieldRealAccountID, usagealertbinding.FieldWebhookID:
			values[i] = new(sql.NullInt64)
		case usagealertbinding.FieldCreatedAt, usagealertbinding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageAlertBinding fields.
func (_m *UsageAlertBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagealertbinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usagealertbinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usagealertbinding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usagealertbinding.FieldRealAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field real_account_id", values[i])
			} else if value.Valid {
				_m.RealAccountID = value.Int64
			}
		case usagealertbinding.FieldWebhookID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field webhook_id", values[i])
			} else if value.Valid {
				_m.WebhookID = value.Int64
			}
		case usagealertbinding.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageAlertBinding.
// This includes values selected through modifiers, order, etc.
func (_m *UsageAlertBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRealAccount queries the "real_account" edge of the UsageAlertBinding entity.
func (_m *UsageAlertBinding) QueryRealAccount() *RealAccountQuery {
	return NewUsageAlertBindingClient(_m.config).QueryRealAccount(_m)
}

// QueryWebhook queries the "webhook" edge of the UsageAlertBinding entity.
func (_m *UsageAlertBinding) QueryWebhook() *UsageAlertWebhookQuery {
	return NewUsageAlertBindingClient(_m.config).QueryWebhook(_m)
}

// Update returns a builder for updating this UsageAlertBinding.
// Note that you need to call UsageAlertBinding.Unwrap() before calling this method if this UsageAlertBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageAlertBinding) Update() *UsageAlertBindingUpdateOne {
	return NewUsageAlertBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageAlertBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageAlertBinding) Unwrap() *UsageAlertBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageAlertBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageAlertBinding) String() string {
	var builder strings.Builder
	builder.WriteString("UsageAlertBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("real_account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RealAccountID))
	builder.WriteString(", ")
	builder.WriteString("webhook_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WebhookID))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// UsageAlertBindings is a parsable slice of UsageAlertBinding.
type UsageAlertBindings []*UsageAlertBinding
