// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagealertwebhook"
)

// UsageAlertWebhookDelete is the builder for deleting a UsageAlertWebhook entity.
type UsageAlertWebhookDelete struct {
	config
	hooks    []Hook
	mutation *UsageAlertWebhookMutation
}

// Where appends a list predicates to the UsageAlertWebhookDelete builder.
func (_d *UsageAlertWebhookDelete) Where(ps ...predicate.UsageAlertWebhook) *UsageAlertWebhookDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UsageAlertWebhookDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UsageAlertWebhookDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UsageAlertWebhookDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usagealertwebhook.Table, sqlgraph.NewFieldSpec(usagealertwebhook.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UsageAlertWebhookDeleteOne is the builder for deleting a single UsageAlertWebhook entity.
type UsageAlertWebhookDeleteOne struct {
	_d *UsageAlertWebhookDelete
}

// Where appends a list predicates to the UsageAlertWebhookDelete builder.
func (_d *UsageAlertWebhookDeleteOne) Where(ps ...predicate.UsageAlertWebhook) *UsageAlertWebhookDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UsageAlertWebhookDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usagealertwebhook.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UsageAlertWebhookDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
