// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagealertbinding"
)

// UsageAlertBindingDelete is the builder for deleting a UsageAlertBinding entity.
type UsageAlertBindingDelete struct {
	config
	hooks    []Hook
	mutation *UsageAlertBindingMutation
}

// Where appends a list predicates to the UsageAlertBindingDelete builder.
func (_d *UsageAlertBindingDelete) Where(ps ...predicate.UsageAlertBinding) *UsageAlertBindingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UsageAlertBindingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UsageAlertBindingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UsageAlertBindingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usagealertbinding.Table, sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UsageAlertBindingDeleteOne is the builder for deleting a single UsageAlertBinding entity.
type UsageAlertBindingDeleteOne struct {
	_d *UsageAlertBindingDelete
}

// Where appends a list predicates to the UsageAlertBindingDelete builder.
func (_d *UsageAlertBindingDeleteOne) Where(ps ...predicate.UsageAlertBinding) *UsageAlertBindingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UsageAlertBindingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usagealertbinding.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UsageAlertBindingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
