// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagealertbinding"
	"github.com/Wei-Shaw/sub2api/ent/usagealertwebhook"
)

// UsageAlertWebhookUpdate is the builder for updating UsageAlertWebhook entities.
type UsageAlertWebhookUpdate struct {
	config
	hooks    []Hook
	mutation *UsageAlertWebhookMutation
}

// Where appends a list predicates to the UsageAlertWebhookUpdate builder.
func (_u *UsageAlertWebhookUpdate) Where(ps ...predicate.UsageAlertWebhook) *UsageAlertWebhookUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageAlertWebhookUpdate) SetUpdatedAt(v time.Time) *UsageAlertWebhookUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UsageAlertWebhookUpdate) SetDeletedAt(v time.Time) *UsageAlertWebhookUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UsageAlertWebhookUpdate) SetNillableDeletedAt(v *time.Time) *UsageAlertWebhookUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UsageAlertWebhookUpdate) ClearDeletedAt() *UsageAlertWebhookUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *UsageAlertWebhookUpdate) SetName(v string) *UsageAlertWebhookUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UsageAlertWebhookUpdate) SetNillableName(v *string) *UsageAlertWebhookUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *UsageAlertWebhookUpdate) SetURL(v string) *UsageAlertWebhookUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *UsageAlertWebhookUpdate) SetNillableURL(v *string) *UsageAlertWebhookUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UsageAlertWebhookUpdate) SetEnabled(v bool) *UsageAlertWebhookUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UsageAlertWebhookUpdate) SetNillableEnabled(v *bool) *UsageAlertWebhookUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *UsageAlertWebhookUpdate) SetRetryCount(v int) *UsageAlertWebhookUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *UsageAlertWebhookUpdate) SetNillableRetryCount(v *int) *UsageAlertWebhookUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *UsageAlertWebhookUpdate) AddRetryCount(v int) *UsageAlertWebhookUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// AddBindingIDs adds the "bindings" edge to the UsageAlertBinding entity by IDs.
func (_u *UsageAlertWebhookUpdate) AddBindingIDs(ids ...int64) *UsageAlertWebhookUpdate {
	_u.mutation.AddBindingIDs(ids...)
	return _u
}

// AddBindings adds the "bindings" edges to the UsageAlertBinding entity.
func (_u *UsageAlertWebhookUpdate) AddBindings(v ...*UsageAlertBinding) *UsageAlertWebhookUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBindingIDs(ids...)
}

// Mutation returns the UsageAlertWebhookMutation object of the builder.
func (_u *UsageAlertWebhookUpdate) Mutation() *UsageAlertWebhookMutation {
	return _u.mutation
}

// ClearBindings clears all "bindings" edges to the UsageAlertBinding entity.
func (_u *UsageAlertWebhookUpdate) ClearBindings() *UsageAlertWebhookUpdate {
	_u.mutation.ClearBindings()
	return _u
}

// RemoveBindingIDs removes the "bindings" edge to UsageAlertBinding entities by IDs.
func (_u *UsageAlertWebhookUpdate) RemoveBindingIDs(ids ...int64) *UsageAlertWebhookUpdate {
	_u.mutation.RemoveBindingIDs(ids...)
	return _u
}

// RemoveBindings removes "bindings" edges to UsageAlertBinding entities.
func (_u *UsageAlertWebhookUpdate) RemoveBindings(v ...*UsageAlertBinding) *UsageAlertWebhookUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBindingIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageAlertWebhookUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageAlertWebhookUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageAlertWebhookUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageAlertWebhookUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageAlertWebhookUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usagealertwebhook.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usagealertwebhook.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usagealertwebhook.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageAlertWebhookUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := usagealertwebhook.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UsageAlertWebhook.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := usagealertwebhook.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "UsageAlertWebhook.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RetryCount(); ok {
		if err := usagealertwebhook.RetryCountValidator(v); err != nil {
			return &ValidationError{Name: "retry_count", err: fmt.Errorf(`ent: validator failed for field "UsageAlertWebhook.retry_count": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageAlertWebhookUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagealertwebhook.Table, usagealertwebhook.Columns, sqlgraph.NewFieldSpec(usagealertwebhook.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagealertwebhook.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usagealertwebhook.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usagealertwebhook.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(usagealertwebhook.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(usagealertwebhook.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(usagealertwebhook.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(usagealertwebhook.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(usagealertwebhook.FieldRetryCount, field.TypeInt, value)
	}
	if _u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   usagealertwebhook.BindingsTable,
			Columns: []string{usagealertwebhook.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBindingsIDs(); len(nodes) > 0 && !_u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   usagealertwebhook.BindingsTable,
			Columns: []string{usagealertwebhook.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   usagealertwebhook.BindingsTable,
			Columns: []string{usagealertwebhook.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagealertwebhook.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageAlertWebhookUpdateOne is the builder for updating a single UsageAlertWebhook entity.
type UsageAlertWebhookUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageAlertWebhookMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageAlertWebhookUpdateOne) SetUpdatedAt(v time.Time) *UsageAlertWebhookUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UsageAlertWebhookUpdateOne) SetDeletedAt(v time.Time) *UsageAlertWebhookUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UsageAlertWebhookUpdateOne) SetNillableDeletedAt(v *time.Time) *UsageAlertWebhookUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UsageAlertWebhookUpdateOne) ClearDeletedAt() *UsageAlertWebhookUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *UsageAlertWebhookUpdateOne) SetName(v string) *UsageAlertWebhookUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UsageAlertWebhookUpdateOne) SetNillableName(v *string) *UsageAlertWebhookUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *UsageAlertWebhookUpdateOne) SetURL(v string) *UsageAlertWebhookUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *UsageAlertWebhookUpdateOne) SetNillableURL(v *string) *UsageAlertWebhookUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UsageAlertWebhookUpdateOne) SetEnabled(v bool) *UsageAlertWebhookUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UsageAlertWebhookUpdateOne) SetNillableEnabled(v *bool) *UsageAlertWebhookUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *UsageAlertWebhookUpdateOne) SetRetryCount(v int) *UsageAlertWebhookUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *UsageAlertWebhookUpdateOne) SetNillableRetryCount(v *int) *UsageAlertWebhookUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *UsageAlertWebhookUpdateOne) AddRetryCount(v int) *UsageAlertWebhookUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// AddBindingIDs adds the "bindings" edge to the UsageAlertBinding entity by IDs.
func (_u *UsageAlertWebhookUpdateOne) AddBindingIDs(ids ...int64) *UsageAlertWebhookUpdateOne {
	_u.mutation.AddBindingIDs(ids...)
	return _u
}

// AddBindings adds the "bindings" edges to the UsageAlertBinding entity.
func (_u *UsageAlertWebhookUpdateOne) AddBindings(v ...*UsageAlertBinding) *UsageAlertWebhookUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBindingIDs(ids...)
}

// Mutation returns the UsageAlertWebhookMutation object of the builder.
func (_u *UsageAlertWebhookUpdateOne) Mutation() *UsageAlertWebhookMutation {
	return _u.mutation
}

// ClearBindings clears all "bindings" edges to the UsageAlertBinding entity.
func (_u *UsageAlertWebhookUpdateOne) ClearBindings() *UsageAlertWebhookUpdateOne {
	_u.mutation.ClearBindings()
	return _u
}

// RemoveBindingIDs removes the "bindings" edge to UsageAlertBinding entities by IDs.
func (_u *UsageAlertWebhookUpdateOne) RemoveBindingIDs(ids ...int64) *UsageAlertWebhookUpdateOne {
	_u.mutation.RemoveBindingIDs(ids...)
	return _u
}

// RemoveBindings removes "bindings" edges to UsageAlertBinding entities.
func (_u *UsageAlertWebhookUpdateOne) RemoveBindings(v ...*UsageAlertBinding) *UsageAlertWebhookUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBindingIDs(ids...)
}

// Where appends a list predicates to the UsageAlertWebhookUpdate builder.
func (_u *UsageAlertWebhookUpdateOne) Where(ps ...predicate.UsageAlertWebhook) *UsageAlertWebhookUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageAlertWebhookUpdateOne) Select(field string, fields ...string) *UsageAlertWebhookUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageAlertWebhook entity.
func (_u *UsageAlertWebhookUpdateOne) Save(ctx context.Context) (*UsageAlertWebhook, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageAlertWebhookUpdateOne) SaveX(ctx context.Context) *UsageAlertWebhook {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageAlertWebhookUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageAlertWebhookUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageAlertWebhookUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usagealertwebhook.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usagealertwebhook.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usagealertwebhook.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageAlertWebhookUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := usagealertwebhook.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UsageAlertWebhook.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := usagealertwebhook.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "UsageAlertWebhook.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RetryCount(); ok {
		if err := usagealertwebhook.RetryCountValidator(v); err != nil {
			return &ValidationError{Name: "retry_count", err: fmt.Errorf(`ent: validator failed for field "UsageAlertWebhook.retry_count": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageAlertWebhookUpdateOne) sqlSave(ctx context.Context) (_node *UsageAlertWebhook, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagealertwebhook.Table, usagealertwebhook.Columns, sqlgraph.NewFieldSpec(usagealertwebhook.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageAlertWebhook.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagealertwebhook.FieldID)
		for _, f := range fields {
			if !usagealertwebhook.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagealertwebhook.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagealertwebhook.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usagealertwebhook.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usagealertwebhook.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(usagealertwebhook.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(usagealertwebhook.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(usagealertwebhook.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(usagealertwebhook.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(usagealertwebhook.FieldRetryCount, field.TypeInt, value)
	}
	if _u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   usagealertwebhook.BindingsTable,
			Columns: []string{usagealertwebhook.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBindingsIDs(); len(nodes) > 0 && !_u.mutation.BindingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   usagealertwebhook.BindingsTable,
			Columns: []string{usagealertwebhook.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   usagealertwebhook.BindingsTable,
			Columns: []string{usagealertwebhook.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UsageAlertWebhook{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagealertwebhook.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
