// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usagealertbinding"
	"github.com/Wei-Shaw/sub2api/ent/usagealertwebhook"
)

// UsageAlertWebhookCreate is the builder for creating a UsageAlertWebhook entity.
type UsageAlertWebhookCreate struct {
	config
	mutation *UsageAlertWebhookMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageAlertWebhookCreate) SetCreatedAt(v time.Time) *UsageAlertWebhookCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageAlertWebhookCreate) SetNillableCreatedAt(v *time.Time) *UsageAlertWebhookCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UsageAlertWebhookCreate) SetUpdatedAt(v time.Time) *UsageAlertWebhookCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UsageAlertWebhookCreate) SetNillableUpdatedAt(v *time.Time) *UsageAlertWebhookCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UsageAlertWebhookCreate) SetDeletedAt(v time.Time) *UsageAlertWebhookCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UsageAlertWebhookCreate) SetNillableDeletedAt(v *time.Time) *UsageAlertWebhookCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UsageAlertWebhookCreate) SetName(v string) *UsageAlertWebhookCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *UsageAlertWebhookCreate) SetType(v string) *UsageAlertWebhookCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *UsageAlertWebhookCreate) SetNillableType(v *string) *UsageAlertWebhookCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *UsageAlertWebhookCreate) SetURL(v string) *UsageAlertWebhookCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *UsageAlertWebhookCreate) SetNillableURL(v *string) *UsageAlertWebhookCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *UsageAlertWebhookCreate) SetConfig(v map[string]interface{}) *UsageAlertWebhookCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *UsageAlertWebhookCreate) SetEnabled(v bool) *UsageAlertWebhookCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *UsageAlertWebhookCreate) SetNillableEnabled(v *bool) *UsageAlertWebhookCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *UsageAlertWebhookCreate) SetRetryCount(v int) *UsageAlertWebhookCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *UsageAlertWebhookCreate) SetNillableRetryCount(v *int) *UsageAlertWebhookCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// AddBindingIDs adds the "bindings" edge to the UsageAlertBinding entity by IDs.
func (_c *UsageAlertWebhookCreate) AddBindingIDs(ids ...int64) *UsageAlertWebhookCreate {
	_c.mutation.AddBindingIDs(ids...)
	return _c
}

// AddBindings adds the "bindings" edges to the UsageAlertBinding entity.
func (_c *UsageAlertWebhookCreate) AddBindings(v ...*UsageAlertBinding) *UsageAlertWebhookCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBindingIDs(ids...)
}

// Mutation returns the UsageAlertWebhookMutation object of the builder.
func (_c *UsageAlertWebhookCreate) Mutation() *UsageAlertWebhookMutation {
	return _c.mutation
}

// Save creates the UsageAlertWebhook in the database.
func (_c *UsageAlertWebhookCreate) Save(ctx context.Context) (*UsageAlertWebhook, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageAlertWebhookCreate) SaveX(ctx context.Context) *UsageAlertWebhook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageAlertWebhookCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageAlertWebhookCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageAlertWebhookCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if usagealertwebhook.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized usagealertwebhook.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := usagealertwebhook.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if usagealertwebhook.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usagealertwebhook.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usagealertwebhook.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := usagealertwebhook.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.Config(); !ok {
		v := usagealertwebhook.DefaultConfig
		_c.mutation.SetConfig(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := usagealertwebhook.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := usagealertwebhook.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageAlertWebhookCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageAlertWebhook.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UsageAlertWebhook.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UsageAlertWebhook.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := usagealertwebhook.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UsageAlertWebhook.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "UsageAlertWebhook.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := usagealertwebhook.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UsageAlertWebhook.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "UsageAlertWebhook.config"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "UsageAlertWebhook.enabled"`)}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "UsageAlertWebhook.retry_count"`)}
	}
	if v, ok := _c.mutation.RetryCount(); ok {
		if err := usagealertwebhook.RetryCountValidator(v); err != nil {
			return &ValidationError{Name: "retry_count", err: fmt.Errorf(`ent: validator failed for field "UsageAlertWebhook.retry_count": %w`, err)}
		}
	}
	return nil
}

func (_c *UsageAlertWebhookCreate) sqlSave(ctx context.Context) (*UsageAlertWebhook, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageAlertWebhookCreate) createSpec() (*UsageAlertWebhook, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageAlertWebhook{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagealertwebhook.Table, sqlgraph.NewFieldSpec(usagealertwebhook.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagealertwebhook.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usagealertwebhook.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(usagealertwebhook.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(usagealertwebhook.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(usagealertwebhook.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(usagealertwebhook.FieldURL, field.TypeString, value)
		_node.URL = &value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(usagealertwebhook.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(usagealertwebhook.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(usagealertwebhook.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if nodes := _c.mutation.BindingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   usagealertwebhook.BindingsTable,
			Columns: []string{usagealertwebhook.BindingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertbinding.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageAlertWebhook.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageAlertWebhookUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageAlertWebhookCreate) OnConflict(opts ...sql.ConflictOption) *UsageAlertWebhookUpsertOne {
	_c.conflict = opts
	return &UsageAlertWebhookUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageAlertWebhook.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageAlertWebhookCreate) OnConflictColumns(columns ...string) *UsageAlertWebhookUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageAlertWebhookUpsertOne{
		create: _c,
	}
}

type (
	// UsageAlertWebhookUpsertOne is the builder for "upsert"-ing
	//  one UsageAlertWebhook node.
	UsageAlertWebhookUpsertOne struct {
		create *UsageAlertWebhookCreate
	}

	// UsageAlertWebhookUpsert is the "OnConflict" setter.
	UsageAlertWebhookUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageAlertWebhookUpsert) SetUpdatedAt(v time.Time) *UsageAlertWebhookUpsert {
	u.Set(usagealertwebhook.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsert) UpdateUpdatedAt() *UsageAlertWebhookUpsert {
	u.SetExcluded(usagealertwebhook.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UsageAlertWebhookUpsert) SetDeletedAt(v time.Time) *UsageAlertWebhookUpsert {
	u.Set(usagealertwebhook.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsert) UpdateDeletedAt() *UsageAlertWebhookUpsert {
	u.SetExcluded(usagealertwebhook.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UsageAlertWebhookUpsert) ClearDeletedAt() *UsageAlertWebhookUpsert {
	u.SetNull(usagealertwebhook.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *UsageAlertWebhookUpsert) SetName(v string) *UsageAlertWebhookUpsert {
	u.Set(usagealertwebhook.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsert) UpdateName() *UsageAlertWebhookUpsert {
	u.SetExcluded(usagealertwebhook.FieldName)
	return u
}

// SetType sets the "type" field.
func (u *UsageAlertWebhookUpsert) SetType(v string) *UsageAlertWebhookUpsert {
	u.Set(usagealertwebhook.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsert) UpdateType() *UsageAlertWebhookUpsert {
	u.SetExcluded(usagealertwebhook.FieldType)
	return u
}

// SetURL sets the "url" field.
func (u *UsageAlertWebhookUpsert) SetURL(v string) *UsageAlertWebhookUpsert {
	u.Set(usagealertwebhook.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsert) UpdateURL() *UsageAlertWebhookUpsert {
	u.SetExcluded(usagealertwebhook.FieldURL)
	return u
}

// ClearURL clears the value of the "url" field.
func (u *UsageAlertWebhookUpsert) ClearURL() *UsageAlertWebhookUpsert {
	u.SetNull(usagealertwebhook.FieldURL)
	return u
}

// SetConfig sets the "config" field.
func (u *UsageAlertWebhookUpsert) SetConfig(v map[string]interface{}) *UsageAlertWebhookUpsert {
	u.Set(usagealertwebhook.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsert) UpdateConfig() *UsageAlertWebhookUpsert {
	u.SetExcluded(usagealertwebhook.FieldConfig)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *UsageAlertWebhookUpsert) SetEnabled(v bool) *UsageAlertWebhookUpsert {
	u.Set(usagealertwebhook.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsert) UpdateEnabled() *UsageAlertWebhookUpsert {
	u.SetExcluded(usagealertwebhook.FieldEnabled)
	return u
}

// SetRetryCount sets the "retry_count" field.
func (u *UsageAlertWebhookUpsert) SetRetryCount(v int) *UsageAlertWebhookUpsert {
	u.Set(usagealertwebhook.FieldRetryCount, v)
	return u
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsert) UpdateRetryCount() *UsageAlertWebhookUpsert {
	u.SetExcluded(usagealertwebhook.FieldRetryCount)
	return u
}

// AddRetryCount adds v to the "retry_count" field.
func (u *UsageAlertWebhookUpsert) AddRetryCount(v int) *UsageAlertWebhookUpsert {
	u.Add(usagealertwebhook.FieldRetryCount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UsageAlertWebhook.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageAlertWebhookUpsertOne) UpdateNewValues() *UsageAlertWebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usagealertwebhook.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageAlertWebhook.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageAlertWebhookUpsertOne) Ignore() *UsageAlertWebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageAlertWebhookUpsertOne) DoNothing() *UsageAlertWebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageAlertWebhookCreate.OnConflict
// documentation for more info.
func (u *UsageAlertWebhookUpsertOne) Update(set func(*UsageAlertWebhookUpsert)) *UsageAlertWebhookUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageAlertWebhookUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageAlertWebhookUpsertOne) SetUpdatedAt(v time.Time) *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertOne) UpdateUpdatedAt() *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UsageAlertWebhookUpsertOne) SetDeletedAt(v time.Time) *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertOne) UpdateDeletedAt() *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UsageAlertWebhookUpsertOne) ClearDeletedAt() *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *UsageAlertWebhookUpsertOne) SetName(v string) *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertOne) UpdateName() *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *UsageAlertWebhookUpsertOne) SetType(v string) *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertOne) UpdateType() *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateType()
	})
}

// SetURL sets the "url" field.
func (u *UsageAlertWebhookUpsertOne) SetURL(v string) *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertOne) UpdateURL() *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateURL()
	})
}

// ClearURL clears the value of the "url" field.
func (u *UsageAlertWebhookUpsertOne) ClearURL() *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.ClearURL()
	})
}

// SetConfig sets the "config" field.
func (u *UsageAlertWebhookUpsertOne) SetConfig(v map[string]interface{}) *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertOne) UpdateConfig() *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateConfig()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UsageAlertWebhookUpsertOne) SetEnabled(v bool) *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertOne) UpdateEnabled() *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateEnabled()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *UsageAlertWebhookUpsertOne) SetRetryCount(v int) *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *UsageAlertWebhookUpsertOne) AddRetryCount(v int) *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertOne) UpdateRetryCount() *UsageAlertWebhookUpsertOne {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateRetryCount()
	})
}

// Exec executes the query.
func (u *UsageAlertWebhookUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageAlertWebhookCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageAlertWebhookUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageAlertWebhookUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageAlertWebhookUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageAlertWebhookCreateBulk is the builder for creating many UsageAlertWebhook entities in bulk.
type UsageAlertWebhookCreateBulk struct {
	config
	err      error
	builders []*UsageAlertWebhookCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageAlertWebhook entities in the database.
func (_c *UsageAlertWebhookCreateBulk) Save(ctx context.Context) ([]*UsageAlertWebhook, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageAlertWebhook, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageAlertWebhookMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageAlertWebhookCreateBulk) SaveX(ctx context.Context) []*UsageAlertWebhook {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageAlertWebhookCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageAlertWebhookCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageAlertWebhook.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageAlertWebhookUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageAlertWebhookCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageAlertWebhookUpsertBulk {
	_c.conflict = opts
	return &UsageAlertWebhookUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageAlertWebhook.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageAlertWebhookCreateBulk) OnConflictColumns(columns ...string) *UsageAlertWebhookUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageAlertWebhookUpsertBulk{
		create: _c,
	}
}

// UsageAlertWebhookUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageAlertWebhook nodes.
type UsageAlertWebhookUpsertBulk struct {
	create *UsageAlertWebhookCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageAlertWebhook.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageAlertWebhookUpsertBulk) UpdateNewValues() *UsageAlertWebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usagealertwebhook.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageAlertWebhook.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageAlertWebhookUpsertBulk) Ignore() *UsageAlertWebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageAlertWebhookUpsertBulk) DoNothing() *UsageAlertWebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageAlertWebhookCreateBulk.OnConflict
// documentation for more info.
func (u *UsageAlertWebhookUpsertBulk) Update(set func(*UsageAlertWebhookUpsert)) *UsageAlertWebhookUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageAlertWebhookUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageAlertWebhookUpsertBulk) SetUpdatedAt(v time.Time) *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertBulk) UpdateUpdatedAt() *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UsageAlertWebhookUpsertBulk) SetDeletedAt(v time.Time) *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertBulk) UpdateDeletedAt() *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UsageAlertWebhookUpsertBulk) ClearDeletedAt() *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *UsageAlertWebhookUpsertBulk) SetName(v string) *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertBulk) UpdateName() *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *UsageAlertWebhookUpsertBulk) SetType(v string) *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertBulk) UpdateType() *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateType()
	})
}

// SetURL sets the "url" field.
func (u *UsageAlertWebhookUpsertBulk) SetURL(v string) *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertBulk) UpdateURL() *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateURL()
	})
}

// ClearURL clears the value of the "url" field.
func (u *UsageAlertWebhookUpsertBulk) ClearURL() *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.ClearURL()
	})
}

// SetConfig sets the "config" field.
func (u *UsageAlertWebhookUpsertBulk) SetConfig(v map[string]interface{}) *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertBulk) UpdateConfig() *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateConfig()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UsageAlertWebhookUpsertBulk) SetEnabled(v bool) *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertBulk) UpdateEnabled() *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateEnabled()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *UsageAlertWebhookUpsertBulk) SetRetryCount(v int) *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *UsageAlertWebhookUpsertBulk) AddRetryCount(v int) *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *UsageAlertWebhookUpsertBulk) UpdateRetryCount() *UsageAlertWebhookUpsertBulk {
	return u.Update(func(s *UsageAlertWebhookUpsert) {
		s.UpdateRetryCount()
	})
}

// Exec executes the query.
func (u *UsageAlertWebhookUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageAlertWebhookCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageAlertWebhookCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageAlertWebhookUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
