// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/realaccount"
	"github.com/Wei-Shaw/sub2api/ent/usagealertrule"
	"github.com/Wei-Shaw/sub2api/ent/usagealertstate"
)

// UsageAlertRuleUpdate is the builder for updating UsageAlertRule entities.
type UsageAlertRuleUpdate struct {
	config
	hooks    []Hook
	mutation *UsageAlertRuleMutation
}

// Where appends a list predicates to the UsageAlertRuleUpdate builder.
func (_u *UsageAlertRuleUpdate) Where(ps ...predicate.UsageAlertRule) *UsageAlertRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageAlertRuleUpdate) SetUpdatedAt(v time.Time) *UsageAlertRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UsageAlertRuleUpdate) SetDeletedAt(v time.Time) *UsageAlertRuleUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UsageAlertRuleUpdate) SetNillableDeletedAt(v *time.Time) *UsageAlertRuleUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UsageAlertRuleUpdate) ClearDeletedAt() *UsageAlertRuleUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *UsageAlertRuleUpdate) SetName(v string) *UsageAlertRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UsageAlertRuleUpdate) SetNillableName(v *string) *UsageAlertRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UsageAlertRuleUpdate) SetPlatform(v string) *UsageAlertRuleUpdate {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UsageAlertRuleUpdate) SetNillablePlatform(v *string) *UsageAlertRuleUpdate {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetRealAccountID sets the "real_account_id" field.
func (_u *UsageAlertRuleUpdate) SetRealAccountID(v int64) *UsageAlertRuleUpdate {
	_u.mutation.SetRealAccountID(v)
	return _u
}

// SetNillableRealAccountID sets the "real_account_id" field if the given value is not nil.
func (_u *UsageAlertRuleUpdate) SetNillableRealAccountID(v *int64) *UsageAlertRuleUpdate {
	if v != nil {
		_u.SetRealAccountID(*v)
	}
	return _u
}

// ClearRealAccountID clears the value of the "real_account_id" field.
func (_u *UsageAlertRuleUpdate) ClearRealAccountID() *UsageAlertRuleUpdate {
	_u.mutation.ClearRealAccountID()
	return _u
}

// SetUsageType sets the "usage_type" field.
func (_u *UsageAlertRuleUpdate) SetUsageType(v string) *UsageAlertRuleUpdate {
	_u.mutation.SetUsageType(v)
	return _u
}

// SetNillableUsageType sets the "usage_type" field if the given value is not nil.
func (_u *UsageAlertRuleUpdate) SetNillableUsageType(v *string) *UsageAlertRuleUpdate {
	if v != nil {
		_u.SetUsageType(*v)
	}
	return _u
}

// SetWindow sets the "window" field.
func (_u *UsageAlertRuleUpdate) SetWindow(v string) *UsageAlertRuleUpdate {
	_u.mutation.SetWindow(v)
	return _u
}

// SetNillableWindow sets the "window" field if the given value is not nil.
func (_u *UsageAlertRuleUpdate) SetNillableWindow(v *string) *UsageAlertRuleUpdate {
	if v != nil {
		_u.SetWindow(*v)
	}
	return _u
}

// SetMetric sets the "metric" field.
func (_u *UsageAlertRuleUpdate) SetMetric(v string) *UsageAlertRuleUpdate {
	_u.mutation.SetMetric(v)
	return _u
}

// SetNillableMetric sets the "metric" field if the given value is not nil.
func (_u *UsageAlertRuleUpdate) SetNillableMetric(v *string) *UsageAlertRuleUpdate {
	if v != nil {
		_u.SetMetric(*v)
	}
	return _u
}

// SetOperator sets the "operator" field.
func (_u *UsageAlertRuleUpdate) SetOperator(v string) *UsageAlertRuleUpdate {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *UsageAlertRuleUpdate) SetNillableOperator(v *string) *UsageAlertRuleUpdate {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// SetThreshold sets the "threshold" field.
func (_u *UsageAlertRuleUpdate) SetThreshold(v float64) *UsageAlertRuleUpdate {
	_u.mutation.ResetThreshold()
	_u.mutation.SetThreshold(v)
	return _u
}

// SetNillableThreshold sets the "threshold" field if the given value is not nil.
func (_u *UsageAlertRuleUpdate) SetNillableThreshold(v *float64) *UsageAlertRuleUpdate {
	if v != nil {
		_u.SetThreshold(*v)
	}
	return _u
}

// AddThreshold adds value to the "threshold" field.
func (_u *UsageAlertRuleUpdate) AddThreshold(v float64) *UsageAlertRuleUpdate {
	_u.mutation.AddThreshold(v)
	return _u
}

// SetMinResetAfterHours sets the "min_reset_after_hours" field.
func (_u *UsageAlertRuleUpdate) SetMinResetAfterHours(v float64) *UsageAlertRuleUpdate {
	_u.mutation.ResetMinResetAfterHours()
	_u.mutation.SetMinResetAfterHours(v)
	return _u
}

// SetNillableMinResetAfterHours sets the "min_reset_after_hours" field if the given value is not nil.
func (_u *UsageAlertRuleUpdate) SetNillableMinResetAfterHours(v *float64) *UsageAlertRuleUpdate {
	if v != nil {
		_u.SetMinResetAfterHours(*v)
	}
	return _u
}

// AddMinResetAfterHours adds value to the "min_reset_after_hours" field.
func (_u *UsageAlertRuleUpdate) AddMinResetAfterHours(v float64) *UsageAlertRuleUpdate {
	_u.mutation.AddMinResetAfterHours(v)
	return _u
}

// ClearMinResetAfterHours clears the value of the "min_reset_after_hours" field.
func (_u *UsageAlertRuleUpdate) ClearMinResetAfterHours() *UsageAlertRuleUpdate {
	_u.mutation.ClearMinResetAfterHours()
	return _u
}

// SetStepPercent sets the "step_percent" field.
func (_u *UsageAlertRuleUpdate) SetStepPercent(v float64) *UsageAlertRuleUpdate {
	_u.mutation.ResetStepPercent()
	_u.mutation.SetStepPercent(v)
	return _u
}

// SetNillableStepPercent sets the "step_percent" field if the given value is not nil.
func (_u *UsageAlertRuleUpdate) SetNillableStepPercent(v *float64) *UsageAlertRuleUpdate {
	if v != nil {
		_u.SetStepPercent(*v)
	}
	return _u
}

// AddStepPercent adds value to the "step_percent" field.
func (_u *UsageAlertRuleUpdate) AddStepPercent(v float64) *UsageAlertRuleUpdate {
	_u.mutation.AddStepPercent(v)
	return _u
}

// ClearStepPercent clears the value of the "step_percent" field.
func (_u *UsageAlertRuleUpdate) ClearStepPercent() *UsageAlertRuleUpdate {
	_u.mutation.ClearStepPercent()
	return _u
}

// SetCooldownMinutes sets the "cooldown_minutes" field.
func (_u *UsageAlertRuleUpdate) SetCooldownMinutes(v int) *UsageAlertRuleUpdate {
	_u.mutation.ResetCooldownMinutes()
	_u.mutation.SetCooldownMinutes(v)
	return _u
}

// SetNillableCooldownMinutes sets the "cooldown_minutes" field if the given value is not nil.
func (_u *UsageAlertRuleUpdate) SetNillableCooldownMinutes(v *int) *UsageAlertRuleUpdate {
	if v != nil {
		_u.SetCooldownMinutes(*v)
	}
	return _u
}

// AddCooldownMinutes adds value to the "cooldown_minutes" field.
func (_u *UsageAlertRuleUpdate) AddCooldownMinutes(v int) *UsageAlertRuleUpdate {
	_u.mutation.AddCooldownMinutes(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UsageAlertRuleUpdate) SetEnabled(v bool) *UsageAlertRuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UsageAlertRuleUpdate) SetNillableEnabled(v *bool) *UsageAlertRuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRealAccount sets the "real_account" edge to the RealAccount entity.
func (_u *UsageAlertRuleUpdate) SetRealAccount(v *RealAccount) *UsageAlertRuleUpdate {
	return _u.SetRealAccountID(v.ID)
}

// AddStateIDs adds the "states" edge to the UsageAlertState entity by IDs.
func (_u *UsageAlertRuleUpdate) AddStateIDs(ids ...int64) *UsageAlertRuleUpdate {
	_u.mutation.AddStateIDs(ids...)
	return _u
}

// AddStates adds the "states" edges to the UsageAlertState entity.
func (_u *UsageAlertRuleUpdate) AddStates(v ...*UsageAlertState) *UsageAlertRuleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStateIDs(ids...)
}

// Mutation returns the UsageAlertRuleMutation object of the builder.
func (_u *UsageAlertRuleUpdate) Mutation() *UsageAlertRuleMutation {
	return _u.mutation
}

// ClearRealAccount clears the "real_account" edge to the RealAccount entity.
func (_u *UsageAlertRuleUpdate) ClearRealAccount() *UsageAlertRuleUpdate {
	_u.mutation.ClearRealAccount()
	return _u
}

// ClearStates clears all "states" edges to the UsageAlertState entity.
func (_u *UsageAlertRuleUpdate) ClearStates() *UsageAlertRuleUpdate {
	_u.mutation.ClearStates()
	return _u
}

// RemoveStateIDs removes the "states" edge to UsageAlertState entities by IDs.
func (_u *UsageAlertRuleUpdate) RemoveStateIDs(ids ...int64) *UsageAlertRuleUpdate {
	_u.mutation.RemoveStateIDs(ids...)
	return _u
}

// RemoveStates removes "states" edges to UsageAlertState entities.
func (_u *UsageAlertRuleUpdate) RemoveStates(v ...*UsageAlertState) *UsageAlertRuleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStateIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageAlertRuleUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageAlertRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageAlertRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageAlertRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageAlertRuleUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usagealertrule.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usagealertrule.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usagealertrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageAlertRuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := usagealertrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := usagealertrule.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UsageType(); ok {
		if err := usagealertrule.UsageTypeValidator(v); err != nil {
			return &ValidationError{Name: "usage_type", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.usage_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Window(); ok {
		if err := usagealertrule.WindowValidator(v); err != nil {
			return &ValidationError{Name: "window", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.window": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Metric(); ok {
		if err := usagealertrule.MetricValidator(v); err != nil {
			return &ValidationError{Name: "metric", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.metric": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operator(); ok {
		if err := usagealertrule.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.operator": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CooldownMinutes(); ok {
		if err := usagealertrule.CooldownMinutesValidator(v); err != nil {
			return &ValidationError{Name: "cooldown_minutes", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.cooldown_minutes": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageAlertRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagealertrule.Table, usagealertrule.Columns, sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagealertrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usagealertrule.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usagealertrule.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(usagealertrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(usagealertrule.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsageType(); ok {
		_spec.SetField(usagealertrule.FieldUsageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Window(); ok {
		_spec.SetField(usagealertrule.FieldWindow, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metric(); ok {
		_spec.SetField(usagealertrule.FieldMetric, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(usagealertrule.FieldOperator, field.TypeString, value)
	}
	if value, ok := _u.mutation.Threshold(); ok {
		_spec.SetField(usagealertrule.FieldThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedThreshold(); ok {
		_spec.AddField(usagealertrule.FieldThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinResetAfterHours(); ok {
		_spec.SetField(usagealertrule.FieldMinResetAfterHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinResetAfterHours(); ok {
		_spec.AddField(usagealertrule.FieldMinResetAfterHours, field.TypeFloat64, value)
	}
	if _u.mutation.MinResetAfterHoursCleared() {
		_spec.ClearField(usagealertrule.FieldMinResetAfterHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.StepPercent(); ok {
		_spec.SetField(usagealertrule.FieldStepPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStepPercent(); ok {
		_spec.AddField(usagealertrule.FieldStepPercent, field.TypeFloat64, value)
	}
	if _u.mutation.StepPercentCleared() {
		_spec.ClearField(usagealertrule.FieldStepPercent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CooldownMinutes(); ok {
		_spec.SetField(usagealertrule.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownMinutes(); ok {
		_spec.AddField(usagealertrule.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(usagealertrule.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.RealAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertrule.RealAccountTable,
			Columns: []string{usagealertrule.RealAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RealAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertrule.RealAccountTable,
			Columns: []string{usagealertrule.RealAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   usagealertrule.StatesTable,
			Columns: []string{usagealertrule.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStatesIDs(); len(nodes) > 0 && !_u.mutation.StatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   usagealertrule.StatesTable,
			Columns: []string{usagealertrule.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   usagealertrule.StatesTable,
			Columns: []string{usagealertrule.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagealertrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageAlertRuleUpdateOne is the builder for updating a single UsageAlertRule entity.
type UsageAlertRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageAlertRuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageAlertRuleUpdateOne) SetUpdatedAt(v time.Time) *UsageAlertRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UsageAlertRuleUpdateOne) SetDeletedAt(v time.Time) *UsageAlertRuleUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UsageAlertRuleUpdateOne) SetNillableDeletedAt(v *time.Time) *UsageAlertRuleUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UsageAlertRuleUpdateOne) ClearDeletedAt() *UsageAlertRuleUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *UsageAlertRuleUpdateOne) SetName(v string) *UsageAlertRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UsageAlertRuleUpdateOne) SetNillableName(v *string) *UsageAlertRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPlatform sets the "platform" field.
func (_u *UsageAlertRuleUpdateOne) SetPlatform(v string) *UsageAlertRuleUpdateOne {
	_u.mutation.SetPlatform(v)
	return _u
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (_u *UsageAlertRuleUpdateOne) SetNillablePlatform(v *string) *UsageAlertRuleUpdateOne {
	if v != nil {
		_u.SetPlatform(*v)
	}
	return _u
}

// SetRealAccountID sets the "real_account_id" field.
func (_u *UsageAlertRuleUpdateOne) SetRealAccountID(v int64) *UsageAlertRuleUpdateOne {
	_u.mutation.SetRealAccountID(v)
	return _u
}

// SetNillableRealAccountID sets the "real_account_id" field if the given value is not nil.
func (_u *UsageAlertRuleUpdateOne) SetNillableRealAccountID(v *int64) *UsageAlertRuleUpdateOne {
	if v != nil {
		_u.SetRealAccountID(*v)
	}
	return _u
}

// ClearRealAccountID clears the value of the "real_account_id" field.
func (_u *UsageAlertRuleUpdateOne) ClearRealAccountID() *UsageAlertRuleUpdateOne {
	_u.mutation.ClearRealAccountID()
	return _u
}

// SetUsageType sets the "usage_type" field.
func (_u *UsageAlertRuleUpdateOne) SetUsageType(v string) *UsageAlertRuleUpdateOne {
	_u.mutation.SetUsageType(v)
	return _u
}

// SetNillableUsageType sets the "usage_type" field if the given value is not nil.
func (_u *UsageAlertRuleUpdateOne) SetNillableUsageType(v *string) *UsageAlertRuleUpdateOne {
	if v != nil {
		_u.SetUsageType(*v)
	}
	return _u
}

// SetWindow sets the "window" field.
func (_u *UsageAlertRuleUpdateOne) SetWindow(v string) *UsageAlertRuleUpdateOne {
	_u.mutation.SetWindow(v)
	return _u
}

// SetNillableWindow sets the "window" field if the given value is not nil.
func (_u *UsageAlertRuleUpdateOne) SetNillableWindow(v *string) *UsageAlertRuleUpdateOne {
	if v != nil {
		_u.SetWindow(*v)
	}
	return _u
}

// SetMetric sets the "metric" field.
func (_u *UsageAlertRuleUpdateOne) SetMetric(v string) *UsageAlertRuleUpdateOne {
	_u.mutation.SetMetric(v)
	return _u
}

// SetNillableMetric sets the "metric" field if the given value is not nil.
func (_u *UsageAlertRuleUpdateOne) SetNillableMetric(v *string) *UsageAlertRuleUpdateOne {
	if v != nil {
		_u.SetMetric(*v)
	}
	return _u
}

// SetOperator sets the "operator" field.
func (_u *UsageAlertRuleUpdateOne) SetOperator(v string) *UsageAlertRuleUpdateOne {
	_u.mutation.SetOperator(v)
	return _u
}

// SetNillableOperator sets the "operator" field if the given value is not nil.
func (_u *UsageAlertRuleUpdateOne) SetNillableOperator(v *string) *UsageAlertRuleUpdateOne {
	if v != nil {
		_u.SetOperator(*v)
	}
	return _u
}

// SetThreshold sets the "threshold" field.
func (_u *UsageAlertRuleUpdateOne) SetThreshold(v float64) *UsageAlertRuleUpdateOne {
	_u.mutation.ResetThreshold()
	_u.mutation.SetThreshold(v)
	return _u
}

// SetNillableThreshold sets the "threshold" field if the given value is not nil.
func (_u *UsageAlertRuleUpdateOne) SetNillableThreshold(v *float64) *UsageAlertRuleUpdateOne {
	if v != nil {
		_u.SetThreshold(*v)
	}
	return _u
}

// AddThreshold adds value to the "threshold" field.
func (_u *UsageAlertRuleUpdateOne) AddThreshold(v float64) *UsageAlertRuleUpdateOne {
	_u.mutation.AddThreshold(v)
	return _u
}

// SetMinResetAfterHours sets the "min_reset_after_hours" field.
func (_u *UsageAlertRuleUpdateOne) SetMinResetAfterHours(v float64) *UsageAlertRuleUpdateOne {
	_u.mutation.ResetMinResetAfterHours()
	_u.mutation.SetMinResetAfterHours(v)
	return _u
}

// SetNillableMinResetAfterHours sets the "min_reset_after_hours" field if the given value is not nil.
func (_u *UsageAlertRuleUpdateOne) SetNillableMinResetAfterHours(v *float64) *UsageAlertRuleUpdateOne {
	if v != nil {
		_u.SetMinResetAfterHours(*v)
	}
	return _u
}

// AddMinResetAfterHours adds value to the "min_reset_after_hours" field.
func (_u *UsageAlertRuleUpdateOne) AddMinResetAfterHours(v float64) *UsageAlertRuleUpdateOne {
	_u.mutation.AddMinResetAfterHours(v)
	return _u
}

// ClearMinResetAfterHours clears the value of the "min_reset_after_hours" field.
func (_u *UsageAlertRuleUpdateOne) ClearMinResetAfterHours() *UsageAlertRuleUpdateOne {
	_u.mutation.ClearMinResetAfterHours()
	return _u
}

// SetStepPercent sets the "step_percent" field.
func (_u *UsageAlertRuleUpdateOne) SetStepPercent(v float64) *UsageAlertRuleUpdateOne {
	_u.mutation.ResetStepPercent()
	_u.mutation.SetStepPercent(v)
	return _u
}

// SetNillableStepPercent sets the "step_percent" field if the given value is not nil.
func (_u *UsageAlertRuleUpdateOne) SetNillableStepPercent(v *float64) *UsageAlertRuleUpdateOne {
	if v != nil {
		_u.SetStepPercent(*v)
	}
	return _u
}

// AddStepPercent adds value to the "step_percent" field.
func (_u *UsageAlertRuleUpdateOne) AddStepPercent(v float64) *UsageAlertRuleUpdateOne {
	_u.mutation.AddStepPercent(v)
	return _u
}

// ClearStepPercent clears the value of the "step_percent" field.
func (_u *UsageAlertRuleUpdateOne) ClearStepPercent() *UsageAlertRuleUpdateOne {
	_u.mutation.ClearStepPercent()
	return _u
}

// SetCooldownMinutes sets the "cooldown_minutes" field.
func (_u *UsageAlertRuleUpdateOne) SetCooldownMinutes(v int) *UsageAlertRuleUpdateOne {
	_u.mutation.ResetCooldownMinutes()
	_u.mutation.SetCooldownMinutes(v)
	return _u
}

// SetNillableCooldownMinutes sets the "cooldown_minutes" field if the given value is not nil.
func (_u *UsageAlertRuleUpdateOne) SetNillableCooldownMinutes(v *int) *UsageAlertRuleUpdateOne {
	if v != nil {
		_u.SetCooldownMinutes(*v)
	}
	return _u
}

// AddCooldownMinutes adds value to the "cooldown_minutes" field.
func (_u *UsageAlertRuleUpdateOne) AddCooldownMinutes(v int) *UsageAlertRuleUpdateOne {
	_u.mutation.AddCooldownMinutes(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UsageAlertRuleUpdateOne) SetEnabled(v bool) *UsageAlertRuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UsageAlertRuleUpdateOne) SetNillableEnabled(v *bool) *UsageAlertRuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetRealAccount sets the "real_account" edge to the RealAccount entity.
func (_u *UsageAlertRuleUpdateOne) SetRealAccount(v *RealAccount) *UsageAlertRuleUpdateOne {
	return _u.SetRealAccountID(v.ID)
}

// AddStateIDs adds the "states" edge to the UsageAlertState entity by IDs.
func (_u *UsageAlertRuleUpdateOne) AddStateIDs(ids ...int64) *UsageAlertRuleUpdateOne {
	_u.mutation.AddStateIDs(ids...)
	return _u
}

// AddStates adds the "states" edges to the UsageAlertState entity.
func (_u *UsageAlertRuleUpdateOne) AddStates(v ...*UsageAlertState) *UsageAlertRuleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStateIDs(ids...)
}

// Mutation returns the UsageAlertRuleMutation object of the builder.
func (_u *UsageAlertRuleUpdateOne) Mutation() *UsageAlertRuleMutation {
	return _u.mutation
}

// ClearRealAccount clears the "real_account" edge to the RealAccount entity.
func (_u *UsageAlertRuleUpdateOne) ClearRealAccount() *UsageAlertRuleUpdateOne {
	_u.mutation.ClearRealAccount()
	return _u
}

// ClearStates clears all "states" edges to the UsageAlertState entity.
func (_u *UsageAlertRuleUpdateOne) ClearStates() *UsageAlertRuleUpdateOne {
	_u.mutation.ClearStates()
	return _u
}

// RemoveStateIDs removes the "states" edge to UsageAlertState entities by IDs.
func (_u *UsageAlertRuleUpdateOne) RemoveStateIDs(ids ...int64) *UsageAlertRuleUpdateOne {
	_u.mutation.RemoveStateIDs(ids...)
	return _u
}

// RemoveStates removes "states" edges to UsageAlertState entities.
func (_u *UsageAlertRuleUpdateOne) RemoveStates(v ...*UsageAlertState) *UsageAlertRuleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStateIDs(ids...)
}

// Where appends a list predicates to the UsageAlertRuleUpdate builder.
func (_u *UsageAlertRuleUpdateOne) Where(ps ...predicate.UsageAlertRule) *UsageAlertRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageAlertRuleUpdateOne) Select(field string, fields ...string) *UsageAlertRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageAlertRule entity.
func (_u *UsageAlertRuleUpdateOne) Save(ctx context.Context) (*UsageAlertRule, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageAlertRuleUpdateOne) SaveX(ctx context.Context) *UsageAlertRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageAlertRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageAlertRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageAlertRuleUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if usagealertrule.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized usagealertrule.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := usagealertrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageAlertRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := usagealertrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Platform(); ok {
		if err := usagealertrule.PlatformValidator(v); err != nil {
			return &ValidationError{Name: "platform", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.platform": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UsageType(); ok {
		if err := usagealertrule.UsageTypeValidator(v); err != nil {
			return &ValidationError{Name: "usage_type", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.usage_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Window(); ok {
		if err := usagealertrule.WindowValidator(v); err != nil {
			return &ValidationError{Name: "window", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.window": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Metric(); ok {
		if err := usagealertrule.MetricValidator(v); err != nil {
			return &ValidationError{Name: "metric", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.metric": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Operator(); ok {
		if err := usagealertrule.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.operator": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CooldownMinutes(); ok {
		if err := usagealertrule.CooldownMinutesValidator(v); err != nil {
			return &ValidationError{Name: "cooldown_minutes", err: fmt.Errorf(`ent: validator failed for field "UsageAlertRule.cooldown_minutes": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageAlertRuleUpdateOne) sqlSave(ctx context.Context) (_node *UsageAlertRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagealertrule.Table, usagealertrule.Columns, sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageAlertRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagealertrule.FieldID)
		for _, f := range fields {
			if !usagealertrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagealertrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagealertrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(usagealertrule.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(usagealertrule.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(usagealertrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Platform(); ok {
		_spec.SetField(usagealertrule.FieldPlatform, field.TypeString, value)
	}
	if value, ok := _u.mutation.UsageType(); ok {
		_spec.SetField(usagealertrule.FieldUsageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Window(); ok {
		_spec.SetField(usagealertrule.FieldWindow, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metric(); ok {
		_spec.SetField(usagealertrule.FieldMetric, field.TypeString, value)
	}
	if value, ok := _u.mutation.Operator(); ok {
		_spec.SetField(usagealertrule.FieldOperator, field.TypeString, value)
	}
	if value, ok := _u.mutation.Threshold(); ok {
		_spec.SetField(usagealertrule.FieldThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedThreshold(); ok {
		_spec.AddField(usagealertrule.FieldThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.MinResetAfterHours(); ok {
		_spec.SetField(usagealertrule.FieldMinResetAfterHours, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMinResetAfterHours(); ok {
		_spec.AddField(usagealertrule.FieldMinResetAfterHours, field.TypeFloat64, value)
	}
	if _u.mutation.MinResetAfterHoursCleared() {
		_spec.ClearField(usagealertrule.FieldMinResetAfterHours, field.TypeFloat64)
	}
	if value, ok := _u.mutation.StepPercent(); ok {
		_spec.SetField(usagealertrule.FieldStepPercent, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedStepPercent(); ok {
		_spec.AddField(usagealertrule.FieldStepPercent, field.TypeFloat64, value)
	}
	if _u.mutation.StepPercentCleared() {
		_spec.ClearField(usagealertrule.FieldStepPercent, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CooldownMinutes(); ok {
		_spec.SetField(usagealertrule.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCooldownMinutes(); ok {
		_spec.AddField(usagealertrule.FieldCooldownMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(usagealertrule.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.RealAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertrule.RealAccountTable,
			Columns: []string{usagealertrule.RealAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RealAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertrule.RealAccountTable,
			Columns: []string{usagealertrule.RealAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   usagealertrule.StatesTable,
			Columns: []string{usagealertrule.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStatesIDs(); len(nodes) > 0 && !_u.mutation.StatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   usagealertrule.StatesTable,
			Columns: []string{usagealertrule.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   usagealertrule.StatesTable,
			Columns: []string{usagealertrule.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UsageAlertRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagealertrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
