// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/realaccount"
	"github.com/Wei-Shaw/sub2api/ent/usagealertrule"
	"github.com/Wei-Shaw/sub2api/ent/usagealertstate"
)

// UsageAlertState is the model entity for the UsageAlertState schema.
type UsageAlertState struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RealAccountID holds the value of the "real_account_id" field.
	RealAccountID int64 `json:"real_account_id,omitempty"`
	// RuleID holds the value of the "rule_id" field.
	RuleID int64 `json:"rule_id,omitempty"`
	// UsageType holds the value of the "usage_type" field.
	UsageType string `json:"usage_type,omitempty"`
	// Window holds the value of the "window" field.
	Window string `json:"window,omitempty"`
	// LastStatus holds the value of the "last_status" field.
	LastStatus string `json:"last_status,omitempty"`
	// LastTriggeredAt holds the value of the "last_triggered_at" field.
	LastTriggeredAt *time.Time `json:"last_triggered_at,omitempty"`
	// LastValue holds the value of the "last_value" field.
	LastValue *float64 `json:"last_value,omitempty"`
	// LastResetAt holds the value of the "last_reset_at" field.
	LastResetAt *time.Time `json:"last_reset_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageAlertStateQuery when eager-loading is set.
	Edges        UsageAlertStateEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsageAlertStateEdges holds the relations/edges for other nodes in the graph.
type UsageAlertStateEdges struct {
	// RealAccount holds the value of the real_account edge.
	RealAccount *RealAccount `json:"real_account,omitempty"`
	// Rule holds the value of the rule edge.
	Rule *UsageAlertRule `json:"rule,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RealAccountOrErr returns the RealAccount value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageAlertStateEdges) RealAccountOrErr() (*RealAccount, error) {
	if e.RealAccount != nil {
		return e.RealAccount, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: realaccount.Label}
	}
	return nil, &NotLoadedError{edge: "real_account"}
}

// RuleOrErr returns the Rule value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageAlertStateEdges) RuleOrErr() (*UsageAlertRule, error) {
	if e.Rule != nil {
		return e.Rule, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: usagealertrule.Label}
	}
	return nil, &NotLoadedError{edge: "rule"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageAlertState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagealertstate.FieldLastValue:
			values[i] = new(sql.NullFloat64)
		case usagealertstate.FieldID, usagealertstate.FieldRealAccountID, usagealertstate.FieldRuleID:
			values[i] = new(sql.NullInt64)
		case usagealertstate.FieldUsageType, usagealertstate.FieldWindow, usagealertstate.FieldLastStatus:
			values[i] = new(sql.NullString)
		case usagealertstate.FieldCreatedAt, usagealertstate.FieldUpdatedAt, usagealertstate.FieldLastTriggeredAt, usagealertstate.FieldLastResetAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageAlertState fields.
func (_m *UsageAlertState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagealertstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usagealertstate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usagealertstate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case usagealertstate.FieldRealAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field real_account_id", values[i])
			} else if value.Valid {
				_m.RealAccountID = value.Int64
			}
		case usagealertstate.FieldRuleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rule_id", values[i])
			} else if value.Valid {
				_m.RuleID = value.Int64
			}
		case usagealertstate.FieldUsageType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field usage_type", values[i])
			} else if value.Valid {
				_m.UsageType = value.String
			}
		case usagealertstate.FieldWindow:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field window", values[i])
			} else if value.Valid {
				_m.Window = value.String
			}
		case usagealertstate.FieldLastStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_status", values[i])
			} else if value.Valid {
				_m.LastStatus = value.String
			}
		case usagealertstate.FieldLastTriggeredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_triggered_at", values[i])
			} else if value.Valid {
				_m.LastTriggeredAt = new(time.Time)
				*_m.LastTriggeredAt = value.Time
			}
		case usagealertstate.FieldLastValue:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field last_value", values[i])
			} else if value.Valid {
				_m.LastValue = new(float64)
				*_m.LastValue = value.Float64
			}
		case usagealertstate.FieldLastResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_reset_at", values[i])
			} else if value.Valid {
				_m.LastResetAt = new(time.Time)
				*_m.LastResetAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageAlertState.
// This includes values selected through modifiers, order, etc.
func (_m *UsageAlertState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRealAccount queries the "real_account" edge of the UsageAlertState entity.
func (_m *UsageAlertState) QueryRealAccount() *RealAccountQuery {
	return NewUsageAlertStateClient(_m.config).QueryRealAccount(_m)
}

// QueryRule queries the "rule" edge of the UsageAlertState entity.
func (_m *UsageAlertState) QueryRule() *UsageAlertRuleQuery {
	return NewUsageAlertStateClient(_m.config).QueryRule(_m)
}

// Update returns a builder for updating this UsageAlertState.
// Note that you need to call UsageAlertState.Unwrap() before calling this method if this UsageAlertState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageAlertState) Update() *UsageAlertStateUpdateOne {
	return NewUsageAlertStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageAlertState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageAlertState) Unwrap() *UsageAlertState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageAlertState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageAlertState) String() string {
	var builder strings.Builder
	builder.WriteString("UsageAlertState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("real_account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RealAccountID))
	builder.WriteString(", ")
	builder.WriteString("rule_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RuleID))
	builder.WriteString(", ")
	builder.WriteString("usage_type=")
	builder.WriteString(_m.UsageType)
	builder.WriteString(", ")
	builder.WriteString("window=")
	builder.WriteString(_m.Window)
	builder.WriteString(", ")
	builder.WriteString("last_status=")
	builder.WriteString(_m.LastStatus)
	builder.WriteString(", ")
	if v := _m.LastTriggeredAt; v != nil {
		builder.WriteString("last_triggered_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastValue; v != nil {
		builder.WriteString("last_value=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastResetAt; v != nil {
		builder.WriteString("last_reset_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UsageAlertStates is a parsable slice of UsageAlertState.
type UsageAlertStates []*UsageAlertState
