// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/realaccount"
	"github.com/Wei-Shaw/sub2api/ent/usagealertrule"
	"github.com/Wei-Shaw/sub2api/ent/usagealertstate"
)

// UsageAlertStateUpdate is the builder for updating UsageAlertState entities.
type UsageAlertStateUpdate struct {
	config
	hooks    []Hook
	mutation *UsageAlertStateMutation
}

// Where appends a list predicates to the UsageAlertStateUpdate builder.
func (_u *UsageAlertStateUpdate) Where(ps ...predicate.UsageAlertState) *UsageAlertStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageAlertStateUpdate) SetUpdatedAt(v time.Time) *UsageAlertStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRealAccountID sets the "real_account_id" field.
func (_u *UsageAlertStateUpdate) SetRealAccountID(v int64) *UsageAlertStateUpdate {
	_u.mutation.SetRealAccountID(v)
	return _u
}

// SetNillableRealAccountID sets the "real_account_id" field if the given value is not nil.
func (_u *UsageAlertStateUpdate) SetNillableRealAccountID(v *int64) *UsageAlertStateUpdate {
	if v != nil {
		_u.SetRealAccountID(*v)
	}
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *UsageAlertStateUpdate) SetRuleID(v int64) *UsageAlertStateUpdate {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *UsageAlertStateUpdate) SetNillableRuleID(v *int64) *UsageAlertStateUpdate {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetUsageType sets the "usage_type" field.
func (_u *UsageAlertStateUpdate) SetUsageType(v string) *UsageAlertStateUpdate {
	_u.mutation.SetUsageType(v)
	return _u
}

// SetNillableUsageType sets the "usage_type" field if the given value is not nil.
func (_u *UsageAlertStateUpdate) SetNillableUsageType(v *string) *UsageAlertStateUpdate {
	if v != nil {
		_u.SetUsageType(*v)
	}
	return _u
}

// SetWindow sets the "window" field.
func (_u *UsageAlertStateUpdate) SetWindow(v string) *UsageAlertStateUpdate {
	_u.mutation.SetWindow(v)
	return _u
}

// SetNillableWindow sets the "window" field if the given value is not nil.
func (_u *UsageAlertStateUpdate) SetNillableWindow(v *string) *UsageAlertStateUpdate {
	if v != nil {
		_u.SetWindow(*v)
	}
	return _u
}

// SetLastStatus sets the "last_status" field.
func (_u *UsageAlertStateUpdate) SetLastStatus(v string) *UsageAlertStateUpdate {
	_u.mutation.SetLastStatus(v)
	return _u
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_u *UsageAlertStateUpdate) SetNillableLastStatus(v *string) *UsageAlertStateUpdate {
	if v != nil {
		_u.SetLastStatus(*v)
	}
	return _u
}

// SetLastTriggeredAt sets the "last_triggered_at" field.
func (_u *UsageAlertStateUpdate) SetLastTriggeredAt(v time.Time) *UsageAlertStateUpdate {
	_u.mutation.SetLastTriggeredAt(v)
	return _u
}

// SetNillableLastTriggeredAt sets the "last_triggered_at" field if the given value is not nil.
func (_u *UsageAlertStateUpdate) SetNillableLastTriggeredAt(v *time.Time) *UsageAlertStateUpdate {
	if v != nil {
		_u.SetLastTriggeredAt(*v)
	}
	return _u
}

// ClearLastTriggeredAt clears the value of the "last_triggered_at" field.
func (_u *UsageAlertStateUpdate) ClearLastTriggeredAt() *UsageAlertStateUpdate {
	_u.mutation.ClearLastTriggeredAt()
	return _u
}

// SetLastValue sets the "last_value" field.
func (_u *UsageAlertStateUpdate) SetLastValue(v float64) *UsageAlertStateUpdate {
	_u.mutation.ResetLastValue()
	_u.mutation.SetLastValue(v)
	return _u
}

// SetNillableLastValue sets the "last_value" field if the given value is not nil.
func (_u *UsageAlertStateUpdate) SetNillableLastValue(v *float64) *UsageAlertStateUpdate {
	if v != nil {
		_u.SetLastValue(*v)
	}
	return _u
}

// AddLastValue adds value to the "last_value" field.
func (_u *UsageAlertStateUpdate) AddLastValue(v float64) *UsageAlertStateUpdate {
	_u.mutation.AddLastValue(v)
	return _u
}

// ClearLastValue clears the value of the "last_value" field.
func (_u *UsageAlertStateUpdate) ClearLastValue() *UsageAlertStateUpdate {
	_u.mutation.ClearLastValue()
	return _u
}

// SetLastResetAt sets the "last_reset_at" field.
func (_u *UsageAlertStateUpdate) SetLastResetAt(v time.Time) *UsageAlertStateUpdate {
	_u.mutation.SetLastResetAt(v)
	return _u
}

// SetNillableLastResetAt sets the "last_reset_at" field if the given value is not nil.
func (_u *UsageAlertStateUpdate) SetNillableLastResetAt(v *time.Time) *UsageAlertStateUpdate {
	if v != nil {
		_u.SetLastResetAt(*v)
	}
	return _u
}

// ClearLastResetAt clears the value of the "last_reset_at" field.
func (_u *UsageAlertStateUpdate) ClearLastResetAt() *UsageAlertStateUpdate {
	_u.mutation.ClearLastResetAt()
	return _u
}

// SetRealAccount sets the "real_account" edge to the RealAccount entity.
func (_u *UsageAlertStateUpdate) SetRealAccount(v *RealAccount) *UsageAlertStateUpdate {
	return _u.SetRealAccountID(v.ID)
}

// SetRule sets the "rule" edge to the UsageAlertRule entity.
func (_u *UsageAlertStateUpdate) SetRule(v *UsageAlertRule) *UsageAlertStateUpdate {
	return _u.SetRuleID(v.ID)
}

// Mutation returns the UsageAlertStateMutation object of the builder.
func (_u *UsageAlertStateUpdate) Mutation() *UsageAlertStateMutation {
	return _u.mutation
}

// ClearRealAccount clears the "real_account" edge to the RealAccount entity.
func (_u *UsageAlertStateUpdate) ClearRealAccount() *UsageAlertStateUpdate {
	_u.mutation.ClearRealAccount()
	return _u
}

// ClearRule clears the "rule" edge to the UsageAlertRule entity.
func (_u *UsageAlertStateUpdate) ClearRule() *UsageAlertStateUpdate {
	_u.mutation.ClearRule()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageAlertStateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageAlertStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageAlertStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageAlertStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageAlertStateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usagealertstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageAlertStateUpdate) check() error {
	if v, ok := _u.mutation.UsageType(); ok {
		if err := usagealertstate.UsageTypeValidator(v); err != nil {
			return &ValidationError{Name: "usage_type", err: fmt.Errorf(`ent: validator failed for field "UsageAlertState.usage_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Window(); ok {
		if err := usagealertstate.WindowValidator(v); err != nil {
			return &ValidationError{Name: "window", err: fmt.Errorf(`ent: validator failed for field "UsageAlertState.window": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastStatus(); ok {
		if err := usagealertstate.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "UsageAlertState.last_status": %w`, err)}
		}
	}
	if _u.mutation.RealAccountCleared() && len(_u.mutation.RealAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageAlertState.real_account"`)
	}
	if _u.mutation.RuleCleared() && len(_u.mutation.RuleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageAlertState.rule"`)
	}
	return nil
}

func (_u *UsageAlertStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagealertstate.Table, usagealertstate.Columns, sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagealertstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsageType(); ok {
		_spec.SetField(usagealertstate.FieldUsageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Window(); ok {
		_spec.SetField(usagealertstate.FieldWindow, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastStatus(); ok {
		_spec.SetField(usagealertstate.FieldLastStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastTriggeredAt(); ok {
		_spec.SetField(usagealertstate.FieldLastTriggeredAt, field.TypeTime, value)
	}
	if _u.mutation.LastTriggeredAtCleared() {
		_spec.ClearField(usagealertstate.FieldLastTriggeredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastValue(); ok {
		_spec.SetField(usagealertstate.FieldLastValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLastValue(); ok {
		_spec.AddField(usagealertstate.FieldLastValue, field.TypeFloat64, value)
	}
	if _u.mutation.LastValueCleared() {
		_spec.ClearField(usagealertstate.FieldLastValue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LastResetAt(); ok {
		_spec.SetField(usagealertstate.FieldLastResetAt, field.TypeTime, value)
	}
	if _u.mutation.LastResetAtCleared() {
		_spec.ClearField(usagealertstate.FieldLastResetAt, field.TypeTime)
	}
	if _u.mutation.RealAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertstate.RealAccountTable,
			Columns: []string{usagealertstate.RealAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RealAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertstate.RealAccountTable,
			Columns: []string{usagealertstate.RealAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RuleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertstate.RuleTable,
			Columns: []string{usagealertstate.RuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RuleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertstate.RuleTable,
			Columns: []string{usagealertstate.RuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagealertstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageAlertStateUpdateOne is the builder for updating a single UsageAlertState entity.
type UsageAlertStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageAlertStateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageAlertStateUpdateOne) SetUpdatedAt(v time.Time) *UsageAlertStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRealAccountID sets the "real_account_id" field.
func (_u *UsageAlertStateUpdateOne) SetRealAccountID(v int64) *UsageAlertStateUpdateOne {
	_u.mutation.SetRealAccountID(v)
	return _u
}

// SetNillableRealAccountID sets the "real_account_id" field if the given value is not nil.
func (_u *UsageAlertStateUpdateOne) SetNillableRealAccountID(v *int64) *UsageAlertStateUpdateOne {
	if v != nil {
		_u.SetRealAccountID(*v)
	}
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *UsageAlertStateUpdateOne) SetRuleID(v int64) *UsageAlertStateUpdateOne {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *UsageAlertStateUpdateOne) SetNillableRuleID(v *int64) *UsageAlertStateUpdateOne {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetUsageType sets the "usage_type" field.
func (_u *UsageAlertStateUpdateOne) SetUsageType(v string) *UsageAlertStateUpdateOne {
	_u.mutation.SetUsageType(v)
	return _u
}

// SetNillableUsageType sets the "usage_type" field if the given value is not nil.
func (_u *UsageAlertStateUpdateOne) SetNillableUsageType(v *string) *UsageAlertStateUpdateOne {
	if v != nil {
		_u.SetUsageType(*v)
	}
	return _u
}

// SetWindow sets the "window" field.
func (_u *UsageAlertStateUpdateOne) SetWindow(v string) *UsageAlertStateUpdateOne {
	_u.mutation.SetWindow(v)
	return _u
}

// SetNillableWindow sets the "window" field if the given value is not nil.
func (_u *UsageAlertStateUpdateOne) SetNillableWindow(v *string) *UsageAlertStateUpdateOne {
	if v != nil {
		_u.SetWindow(*v)
	}
	return _u
}

// SetLastStatus sets the "last_status" field.
func (_u *UsageAlertStateUpdateOne) SetLastStatus(v string) *UsageAlertStateUpdateOne {
	_u.mutation.SetLastStatus(v)
	return _u
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_u *UsageAlertStateUpdateOne) SetNillableLastStatus(v *string) *UsageAlertStateUpdateOne {
	if v != nil {
		_u.SetLastStatus(*v)
	}
	return _u
}

// SetLastTriggeredAt sets the "last_triggered_at" field.
func (_u *UsageAlertStateUpdateOne) SetLastTriggeredAt(v time.Time) *UsageAlertStateUpdateOne {
	_u.mutation.SetLastTriggeredAt(v)
	return _u
}

// SetNillableLastTriggeredAt sets the "last_triggered_at" field if the given value is not nil.
func (_u *UsageAlertStateUpdateOne) SetNillableLastTriggeredAt(v *time.Time) *UsageAlertStateUpdateOne {
	if v != nil {
		_u.SetLastTriggeredAt(*v)
	}
	return _u
}

// ClearLastTriggeredAt clears the value of the "last_triggered_at" field.
func (_u *UsageAlertStateUpdateOne) ClearLastTriggeredAt() *UsageAlertStateUpdateOne {
	_u.mutation.ClearLastTriggeredAt()
	return _u
}

// SetLastValue sets the "last_value" field.
func (_u *UsageAlertStateUpdateOne) SetLastValue(v float64) *UsageAlertStateUpdateOne {
	_u.mutation.ResetLastValue()
	_u.mutation.SetLastValue(v)
	return _u
}

// SetNillableLastValue sets the "last_value" field if the given value is not nil.
func (_u *UsageAlertStateUpdateOne) SetNillableLastValue(v *float64) *UsageAlertStateUpdateOne {
	if v != nil {
		_u.SetLastValue(*v)
	}
	return _u
}

// AddLastValue adds value to the "last_value" field.
func (_u *UsageAlertStateUpdateOne) AddLastValue(v float64) *UsageAlertStateUpdateOne {
	_u.mutation.AddLastValue(v)
	return _u
}

// ClearLastValue clears the value of the "last_value" field.
func (_u *UsageAlertStateUpdateOne) ClearLastValue() *UsageAlertStateUpdateOne {
	_u.mutation.ClearLastValue()
	return _u
}

// SetLastResetAt sets the "last_reset_at" field.
func (_u *UsageAlertStateUpdateOne) SetLastResetAt(v time.Time) *UsageAlertStateUpdateOne {
	_u.mutation.SetLastResetAt(v)
	return _u
}

// SetNillableLastResetAt sets the "last_reset_at" field if the given value is not nil.
func (_u *UsageAlertStateUpdateOne) SetNillableLastResetAt(v *time.Time) *UsageAlertStateUpdateOne {
	if v != nil {
		_u.SetLastResetAt(*v)
	}
	return _u
}

// ClearLastResetAt clears the value of the "last_reset_at" field.
func (_u *UsageAlertStateUpdateOne) ClearLastResetAt() *UsageAlertStateUpdateOne {
	_u.mutation.ClearLastResetAt()
	return _u
}

// SetRealAccount sets the "real_account" edge to the RealAccount entity.
func (_u *UsageAlertStateUpdateOne) SetRealAccount(v *RealAccount) *UsageAlertStateUpdateOne {
	return _u.SetRealAccountID(v.ID)
}

// SetRule sets the "rule" edge to the UsageAlertRule entity.
func (_u *UsageAlertStateUpdateOne) SetRule(v *UsageAlertRule) *UsageAlertStateUpdateOne {
	return _u.SetRuleID(v.ID)
}

// Mutation returns the UsageAlertStateMutation object of the builder.
func (_u *UsageAlertStateUpdateOne) Mutation() *UsageAlertStateMutation {
	return _u.mutation
}

// ClearRealAccount clears the "real_account" edge to the RealAccount entity.
func (_u *UsageAlertStateUpdateOne) ClearRealAccount() *UsageAlertStateUpdateOne {
	_u.mutation.ClearRealAccount()
	return _u
}

// ClearRule clears the "rule" edge to the UsageAlertRule entity.
func (_u *UsageAlertStateUpdateOne) ClearRule() *UsageAlertStateUpdateOne {
	_u.mutation.ClearRule()
	return _u
}

// Where appends a list predicates to the UsageAlertStateUpdate builder.
func (_u *UsageAlertStateUpdateOne) Where(ps ...predicate.UsageAlertState) *UsageAlertStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageAlertStateUpdateOne) Select(field string, fields ...string) *UsageAlertStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageAlertState entity.
func (_u *UsageAlertStateUpdateOne) Save(ctx context.Context) (*UsageAlertState, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageAlertStateUpdateOne) SaveX(ctx context.Context) *UsageAlertState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageAlertStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageAlertStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageAlertStateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usagealertstate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageAlertStateUpdateOne) check() error {
	if v, ok := _u.mutation.UsageType(); ok {
		if err := usagealertstate.UsageTypeValidator(v); err != nil {
			return &ValidationError{Name: "usage_type", err: fmt.Errorf(`ent: validator failed for field "UsageAlertState.usage_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Window(); ok {
		if err := usagealertstate.WindowValidator(v); err != nil {
			return &ValidationError{Name: "window", err: fmt.Errorf(`ent: validator failed for field "UsageAlertState.window": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastStatus(); ok {
		if err := usagealertstate.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "UsageAlertState.last_status": %w`, err)}
		}
	}
	if _u.mutation.RealAccountCleared() && len(_u.mutation.RealAccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageAlertState.real_account"`)
	}
	if _u.mutation.RuleCleared() && len(_u.mutation.RuleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageAlertState.rule"`)
	}
	return nil
}

func (_u *UsageAlertStateUpdateOne) sqlSave(ctx context.Context) (_node *UsageAlertState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagealertstate.Table, usagealertstate.Columns, sqlgraph.NewFieldSpec(usagealertstate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageAlertState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagealertstate.FieldID)
		for _, f := range fields {
			if !usagealertstate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagealertstate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagealertstate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsageType(); ok {
		_spec.SetField(usagealertstate.FieldUsageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Window(); ok {
		_spec.SetField(usagealertstate.FieldWindow, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastStatus(); ok {
		_spec.SetField(usagealertstate.FieldLastStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastTriggeredAt(); ok {
		_spec.SetField(usagealertstate.FieldLastTriggeredAt, field.TypeTime, value)
	}
	if _u.mutation.LastTriggeredAtCleared() {
		_spec.ClearField(usagealertstate.FieldLastTriggeredAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastValue(); ok {
		_spec.SetField(usagealertstate.FieldLastValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLastValue(); ok {
		_spec.AddField(usagealertstate.FieldLastValue, field.TypeFloat64, value)
	}
	if _u.mutation.LastValueCleared() {
		_spec.ClearField(usagealertstate.FieldLastValue, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LastResetAt(); ok {
		_spec.SetField(usagealertstate.FieldLastResetAt, field.TypeTime, value)
	}
	if _u.mutation.LastResetAtCleared() {
		_spec.ClearField(usagealertstate.FieldLastResetAt, field.TypeTime)
	}
	if _u.mutation.RealAccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertstate.RealAccountTable,
			Columns: []string{usagealertstate.RealAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RealAccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertstate.RealAccountTable,
			Columns: []string{usagealertstate.RealAccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(realaccount.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RuleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertstate.RuleTable,
			Columns: []string{usagealertstate.RuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RuleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usagealertstate.RuleTable,
			Columns: []string{usagealertstate.RuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UsageAlertState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagealertstate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
