// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/realaccount"
	"github.com/Wei-Shaw/sub2api/ent/usagealertrule"
	"github.com/Wei-Shaw/sub2api/ent/usagealertstate"
)

// UsageAlertRuleQuery is the builder for querying UsageAlertRule entities.
type UsageAlertRuleQuery struct {
	config
	ctx             *QueryContext
	order           []usagealertrule.OrderOption
	inters          []Interceptor
	predicates      []predicate.UsageAlertRule
	withRealAccount *RealAccountQuery
	withStates      *UsageAlertStateQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UsageAlertRuleQuery builder.
func (_q *UsageAlertRuleQuery) Where(ps ...predicate.UsageAlertRule) *UsageAlertRuleQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *UsageAlertRuleQuery) Limit(limit int) *UsageAlertRuleQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *UsageAlertRuleQuery) Offset(offset int) *UsageAlertRuleQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *UsageAlertRuleQuery) Unique(unique bool) *UsageAlertRuleQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *UsageAlertRuleQuery) Order(o ...usagealertrule.OrderOption) *UsageAlertRuleQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRealAccount chains the current query on the "real_account" edge.
func (_q *UsageAlertRuleQuery) QueryRealAccount() *RealAccountQuery {
	query := (&RealAccountClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usagealertrule.Table, usagealertrule.FieldID, selector),
			sqlgraph.To(realaccount.Table, realaccount.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, usagealertrule.RealAccountTable, usagealertrule.RealAccountColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStates chains the current query on the "states" edge.
func (_q *UsageAlertRuleQuery) QueryStates() *UsageAlertStateQuery {
	query := (&UsageAlertStateClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usagealertrule.Table, usagealertrule.FieldID, selector),
			sqlgraph.To(usagealertstate.Table, usagealertstate.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, usagealertrule.StatesTable, usagealertrule.StatesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UsageAlertRule entity from the query.
// Returns a *NotFoundError when no UsageAlertRule was found.
func (_q *UsageAlertRuleQuery) First(ctx context.Context) (*UsageAlertRule, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usagealertrule.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *UsageAlertRuleQuery) FirstX(ctx context.Context) *UsageAlertRule {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UsageAlertRule ID from the query.
// Returns a *NotFoundError when no UsageAlertRule ID was found.
func (_q *UsageAlertRuleQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usagealertrule.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *UsageAlertRuleQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UsageAlertRule entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UsageAlertRule entity is found.
// Returns a *NotFoundError when no UsageAlertRule entities are found.
func (_q *UsageAlertRuleQuery) Only(ctx context.Context) (*UsageAlertRule, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usagealertrule.Label}
	default:
		return nil, &NotSingularError{usagealertrule.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *UsageAlertRuleQuery) OnlyX(ctx context.Context) *UsageAlertRule {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UsageAlertRule ID in the query.
// Returns a *NotSingularError when more than one UsageAlertRule ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *UsageAlertRuleQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usagealertrule.Label}
	default:
		err = &NotSingularError{usagealertrule.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *UsageAlertRuleQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UsageAlertRules.
func (_q *UsageAlertRuleQuery) All(ctx context.Context) ([]*UsageAlertRule, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UsageAlertRule, *UsageAlertRuleQuery]()
	return withInterceptors[[]*UsageAlertRule](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *UsageAlertRuleQuery) AllX(ctx context.Context) []*UsageAlertRule {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UsageAlertRule IDs.
func (_q *UsageAlertRuleQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(usagealertrule.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *UsageAlertRuleQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *UsageAlertRuleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*UsageAlertRuleQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *UsageAlertRuleQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *UsageAlertRuleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *UsageAlertRuleQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UsageAlertRuleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *UsageAlertRuleQuery) Clone() *UsageAlertRuleQuery {
	if _q == nil {
		return nil
	}
	return &UsageAlertRuleQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]usagealertrule.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.UsageAlertRule{}, _q.predicates...),
		withRealAccount: _q.withRealAccount.Clone(),
		withStates:      _q.withStates.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRealAccount tells the query-builder to eager-load the nodes that are connected to
// the "real_account" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UsageAlertRuleQuery) WithRealAccount(opts ...func(*RealAccountQuery)) *UsageAlertRuleQuery {
	query := (&RealAccountClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRealAccount = query
	return _q
}

// WithStates tells the query-builder to eager-load the nodes that are connected to
// the "states" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *UsageAlertRuleQuery) WithStates(opts ...func(*UsageAlertStateQuery)) *UsageAlertRuleQuery {
	query := (&UsageAlertStateClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStates = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UsageAlertRule.Query().
//		GroupBy(usagealertrule.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *UsageAlertRuleQuery) GroupBy(field string, fields ...string) *UsageAlertRuleGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UsageAlertRuleGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = usagealertrule.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.UsageAlertRule.Query().
//		Select(usagealertrule.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *UsageAlertRuleQuery) Select(fields ...string) *UsageAlertRuleSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &UsageAlertRuleSelect{UsageAlertRuleQuery: _q}
	sbuild.label = usagealertrule.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UsageAlertRuleSelect configured with the given aggregations.
func (_q *UsageAlertRuleQuery) Aggregate(fns ...AggregateFunc) *UsageAlertRuleSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *UsageAlertRuleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !usagealertrule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *UsageAlertRuleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UsageAlertRule, error) {
	var (
		nodes       = []*UsageAlertRule{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withRealAccount != nil,
			_q.withStates != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UsageAlertRule).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UsageAlertRule{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRealAccount; query != nil {
		if err := _q.loadRealAccount(ctx, query, nodes, nil,
			func(n *UsageAlertRule, e *RealAccount) { n.Edges.RealAccount = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withStates; query != nil {
		if err := _q.loadStates(ctx, query, nodes,
			func(n *UsageAlertRule) { n.Edges.States = []*UsageAlertState{} },
			func(n *UsageAlertRule, e *UsageAlertState) { n.Edges.States = append(n.Edges.States, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *UsageAlertRuleQuery) loadRealAccount(ctx context.Context, query *RealAccountQuery, nodes []*UsageAlertRule, init func(*UsageAlertRule), assign func(*UsageAlertRule, *RealAccount)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UsageAlertRule)
	for i := range nodes {
		if nodes[i].RealAccountID == nil {
			continue
		}
		fk := *nodes[i].RealAccountID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(realaccount.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "real_account_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *UsageAlertRuleQuery) loadStates(ctx context.Context, query *UsageAlertStateQuery, nodes []*UsageAlertRule, init func(*UsageAlertRule), assign func(*UsageAlertRule, *UsageAlertState)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*UsageAlertRule)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(usagealertstate.FieldRuleID)
	}
	query.Where(predicate.UsageAlertState(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(usagealertrule.StatesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.RuleID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "rule_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *UsageAlertRuleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *UsageAlertRuleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usagealertrule.Table, usagealertrule.Columns, sqlgraph.NewFieldSpec(usagealertrule.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagealertrule.FieldID)
		for i := range fields {
			if fields[i] != usagealertrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withRealAccount != nil {
			_spec.Node.AddColumnOnce(usagealertrule.FieldRealAccountID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *UsageAlertRuleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(usagealertrule.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = usagealertrule.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *UsageAlertRuleQuery) ForUpdate(opts ...sql.LockOption) *UsageAlertRuleQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *UsageAlertRuleQuery) ForShare(opts ...sql.LockOption) *UsageAlertRuleQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// UsageAlertRuleGroupBy is the group-by builder for UsageAlertRule entities.
type UsageAlertRuleGroupBy struct {
	selector
	build *UsageAlertRuleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *UsageAlertRuleGroupBy) Aggregate(fns ...AggregateFunc) *UsageAlertRuleGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *UsageAlertRuleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsageAlertRuleQuery, *UsageAlertRuleGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *UsageAlertRuleGroupBy) sqlScan(ctx context.Context, root *UsageAlertRuleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UsageAlertRuleSelect is the builder for selecting fields of UsageAlertRule entities.
type UsageAlertRuleSelect struct {
	*UsageAlertRuleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *UsageAlertRuleSelect) Aggregate(fns ...AggregateFunc) *UsageAlertRuleSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *UsageAlertRuleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsageAlertRuleQuery, *UsageAlertRuleSelect](ctx, _s.UsageAlertRuleQuery, _s, _s.inters, v)
}

func (_s *UsageAlertRuleSelect) sqlScan(ctx context.Context, root *UsageAlertRuleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
