// Code generated by ent, DO NOT EDIT.

package usagealertstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usagealertstate type in the database.
	Label = "usage_alert_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRealAccountID holds the string denoting the real_account_id field in the database.
	FieldRealAccountID = "real_account_id"
	// FieldRuleID holds the string denoting the rule_id field in the database.
	FieldRuleID = "rule_id"
	// FieldQuotaDimension holds the string denoting the quota_dimension field in the database.
	FieldQuotaDimension = "quota_dimension"
	// FieldWindow holds the string denoting the window field in the database.
	FieldWindow = "window"
	// FieldLastStatus holds the string denoting the last_status field in the database.
	FieldLastStatus = "last_status"
	// FieldLastTriggeredAt holds the string denoting the last_triggered_at field in the database.
	FieldLastTriggeredAt = "last_triggered_at"
	// FieldLastValue holds the string denoting the last_value field in the database.
	FieldLastValue = "last_value"
	// FieldLastResetAt holds the string denoting the last_reset_at field in the database.
	FieldLastResetAt = "last_reset_at"
	// EdgeRealAccount holds the string denoting the real_account edge name in mutations.
	EdgeRealAccount = "real_account"
	// EdgeRule holds the string denoting the rule edge name in mutations.
	EdgeRule = "rule"
	// Table holds the table name of the usagealertstate in the database.
	Table = "usage_alert_states"
	// RealAccountTable is the table that holds the real_account relation/edge.
	RealAccountTable = "usage_alert_states"
	// RealAccountInverseTable is the table name for the RealAccount entity.
	// It exists in this package in order to avoid circular dependency with the "realaccount" package.
	RealAccountInverseTable = "real_accounts"
	// RealAccountColumn is the table column denoting the real_account relation/edge.
	RealAccountColumn = "real_account_id"
	// RuleTable is the table that holds the rule relation/edge.
	RuleTable = "usage_alert_states"
	// RuleInverseTable is the table name for the UsageAlertRule entity.
	// It exists in this package in order to avoid circular dependency with the "usagealertrule" package.
	RuleInverseTable = "usage_alert_rules"
	// RuleColumn is the table column denoting the rule relation/edge.
	RuleColumn = "rule_id"
)

// Columns holds all SQL columns for usagealertstate fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRealAccountID,
	FieldRuleID,
	FieldQuotaDimension,
	FieldWindow,
	FieldLastStatus,
	FieldLastTriggeredAt,
	FieldLastValue,
	FieldLastResetAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultQuotaDimension holds the default value on creation for the "quota_dimension" field.
	DefaultQuotaDimension string
	// QuotaDimensionValidator is a validator for the "quota_dimension" field. It is called by the builders before save.
	QuotaDimensionValidator func(string) error
	// WindowValidator is a validator for the "window" field. It is called by the builders before save.
	WindowValidator func(string) error
	// DefaultLastStatus holds the default value on creation for the "last_status" field.
	DefaultLastStatus string
	// LastStatusValidator is a validator for the "last_status" field. It is called by the builders before save.
	LastStatusValidator func(string) error
)

// OrderOption defines the ordering options for the UsageAlertState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRealAccountID orders the results by the real_account_id field.
func ByRealAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealAccountID, opts...).ToFunc()
}

// ByRuleID orders the results by the rule_id field.
func ByRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleID, opts...).ToFunc()
}

// ByQuotaDimension orders the results by the quota_dimension field.
func ByQuotaDimension(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaDimension, opts...).ToFunc()
}

// ByWindow orders the results by the window field.
func ByWindow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindow, opts...).ToFunc()
}

// ByLastStatus orders the results by the last_status field.
func ByLastStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastStatus, opts...).ToFunc()
}

// ByLastTriggeredAt orders the results by the last_triggered_at field.
func ByLastTriggeredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTriggeredAt, opts...).ToFunc()
}

// ByLastValue orders the results by the last_value field.
func ByLastValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastValue, opts...).ToFunc()
}

// ByLastResetAt orders the results by the last_reset_at field.
func ByLastResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastResetAt, opts...).ToFunc()
}

// ByRealAccountField orders the results by real_account field.
func ByRealAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRealAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByRuleField orders the results by rule field.
func ByRuleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRuleStep(), sql.OrderByField(field, opts...))
	}
}
func newRealAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RealAccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RealAccountTable, RealAccountColumn),
	)
}
func newRuleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RuleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RuleTable, RuleColumn),
	)
}
