// Code generated by ent, DO NOT EDIT.

package usagealertrule

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usagealertrule type in the database.
	Label = "usage_alert_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldRealAccountID holds the string denoting the real_account_id field in the database.
	FieldRealAccountID = "real_account_id"
	// FieldQuotaDimension holds the string denoting the quota_dimension field in the database.
	FieldQuotaDimension = "quota_dimension"
	// FieldWindow holds the string denoting the window field in the database.
	FieldWindow = "window"
	// FieldMetric holds the string denoting the metric field in the database.
	FieldMetric = "metric"
	// FieldOperator holds the string denoting the operator field in the database.
	FieldOperator = "operator"
	// FieldThreshold holds the string denoting the threshold field in the database.
	FieldThreshold = "threshold"
	// FieldMinResetAfterHours holds the string denoting the min_reset_after_hours field in the database.
	FieldMinResetAfterHours = "min_reset_after_hours"
	// FieldStepPercent holds the string denoting the step_percent field in the database.
	FieldStepPercent = "step_percent"
	// FieldCooldownMinutes holds the string denoting the cooldown_minutes field in the database.
	FieldCooldownMinutes = "cooldown_minutes"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// EdgeRealAccount holds the string denoting the real_account edge name in mutations.
	EdgeRealAccount = "real_account"
	// EdgeStates holds the string denoting the states edge name in mutations.
	EdgeStates = "states"
	// Table holds the table name of the usagealertrule in the database.
	Table = "usage_alert_rules"
	// RealAccountTable is the table that holds the real_account relation/edge.
	RealAccountTable = "usage_alert_rules"
	// RealAccountInverseTable is the table name for the RealAccount entity.
	// It exists in this package in order to avoid circular dependency with the "realaccount" package.
	RealAccountInverseTable = "real_accounts"
	// RealAccountColumn is the table column denoting the real_account relation/edge.
	RealAccountColumn = "real_account_id"
	// StatesTable is the table that holds the states relation/edge.
	StatesTable = "usage_alert_states"
	// StatesInverseTable is the table name for the UsageAlertState entity.
	// It exists in this package in order to avoid circular dependency with the "usagealertstate" package.
	StatesInverseTable = "usage_alert_states"
	// StatesColumn is the table column denoting the states relation/edge.
	StatesColumn = "rule_id"
)

// Columns holds all SQL columns for usagealertrule fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldPlatform,
	FieldRealAccountID,
	FieldQuotaDimension,
	FieldWindow,
	FieldMetric,
	FieldOperator,
	FieldThreshold,
	FieldMinResetAfterHours,
	FieldStepPercent,
	FieldCooldownMinutes,
	FieldEnabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformValidator is a validator for the "platform" field. It is called by the builders before save.
	PlatformValidator func(string) error
	// DefaultQuotaDimension holds the default value on creation for the "quota_dimension" field.
	DefaultQuotaDimension string
	// QuotaDimensionValidator is a validator for the "quota_dimension" field. It is called by the builders before save.
	QuotaDimensionValidator func(string) error
	// WindowValidator is a validator for the "window" field. It is called by the builders before save.
	WindowValidator func(string) error
	// MetricValidator is a validator for the "metric" field. It is called by the builders before save.
	MetricValidator func(string) error
	// OperatorValidator is a validator for the "operator" field. It is called by the builders before save.
	OperatorValidator func(string) error
	// DefaultCooldownMinutes holds the default value on creation for the "cooldown_minutes" field.
	DefaultCooldownMinutes int
	// CooldownMinutesValidator is a validator for the "cooldown_minutes" field. It is called by the builders before save.
	CooldownMinutesValidator func(int) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the UsageAlertRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByRealAccountID orders the results by the real_account_id field.
func ByRealAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealAccountID, opts...).ToFunc()
}

// ByQuotaDimension orders the results by the quota_dimension field.
func ByQuotaDimension(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaDimension, opts...).ToFunc()
}

// ByWindow orders the results by the window field.
func ByWindow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWindow, opts...).ToFunc()
}

// ByMetric orders the results by the metric field.
func ByMetric(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMetric, opts...).ToFunc()
}

// ByOperator orders the results by the operator field.
func ByOperator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperator, opts...).ToFunc()
}

// ByThreshold orders the results by the threshold field.
func ByThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThreshold, opts...).ToFunc()
}

// ByMinResetAfterHours orders the results by the min_reset_after_hours field.
func ByMinResetAfterHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinResetAfterHours, opts...).ToFunc()
}

// ByStepPercent orders the results by the step_percent field.
func ByStepPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStepPercent, opts...).ToFunc()
}

// ByCooldownMinutes orders the results by the cooldown_minutes field.
func ByCooldownMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCooldownMinutes, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByRealAccountField orders the results by real_account field.
func ByRealAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRealAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByStatesCount orders the results by states count.
func ByStatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newStatesStep(), opts...)
	}
}

// ByStates orders the results by states terms.
func ByStates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRealAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RealAccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RealAccountTable, RealAccountColumn),
	)
}
func newStatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, StatesTable, StatesColumn),
	)
}
