// Code generated by ent, DO NOT EDIT.

package usagealertbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usagealertbinding type in the database.
	Label = "usage_alert_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRealAccountID holds the string denoting the real_account_id field in the database.
	FieldRealAccountID = "real_account_id"
	// FieldWebhookID holds the string denoting the webhook_id field in the database.
	FieldWebhookID = "webhook_id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// EdgeRealAccount holds the string denoting the real_account edge name in mutations.
	EdgeRealAccount = "real_account"
	// EdgeWebhook holds the string denoting the webhook edge name in mutations.
	EdgeWebhook = "webhook"
	// Table holds the table name of the usagealertbinding in the database.
	Table = "usage_alert_bindings"
	// RealAccountTable is the table that holds the real_account relation/edge.
	RealAccountTable = "usage_alert_bindings"
	// RealAccountInverseTable is the table name for the RealAccount entity.
	// It exists in this package in order to avoid circular dependency with the "realaccount" package.
	RealAccountInverseTable = "real_accounts"
	// RealAccountColumn is the table column denoting the real_account relation/edge.
	RealAccountColumn = "real_account_id"
	// WebhookTable is the table that holds the webhook relation/edge.
	WebhookTable = "usage_alert_bindings"
	// WebhookInverseTable is the table name for the UsageAlertWebhook entity.
	// It exists in this package in order to avoid circular dependency with the "usagealertwebhook" package.
	WebhookInverseTable = "usage_alert_webhooks"
	// WebhookColumn is the table column denoting the webhook relation/edge.
	WebhookColumn = "webhook_id"
)

// Columns holds all SQL columns for usagealertbinding fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRealAccountID,
	FieldWebhookID,
	FieldEnabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the UsageAlertBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRealAccountID orders the results by the real_account_id field.
func ByRealAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealAccountID, opts...).ToFunc()
}

// ByWebhookID orders the results by the webhook_id field.
func ByWebhookID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebhookID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByRealAccountField orders the results by real_account field.
func ByRealAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRealAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByWebhookField orders the results by webhook field.
func ByWebhookField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWebhookStep(), sql.OrderByField(field, opts...))
	}
}
func newRealAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RealAccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, RealAccountTable, RealAccountColumn),
	)
}
func newWebhookStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WebhookInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, WebhookTable, WebhookColumn),
	)
}
