// Code generated by ent, DO NOT EDIT.

package usagealertbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// RealAccountID applies equality check predicate on the "real_account_id" field. It's identical to RealAccountIDEQ.
func RealAccountID(v int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldEQ(FieldRealAccountID, v))
}

// WebhookID applies equality check predicate on the "webhook_id" field. It's identical to WebhookIDEQ.
func WebhookID(v int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldEQ(FieldWebhookID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// RealAccountIDEQ applies the EQ predicate on the "real_account_id" field.
func RealAccountIDEQ(v int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldEQ(FieldRealAccountID, v))
}

// RealAccountIDNEQ applies the NEQ predicate on the "real_account_id" field.
func RealAccountIDNEQ(v int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldNEQ(FieldRealAccountID, v))
}

// RealAccountIDIn applies the In predicate on the "real_account_id" field.
func RealAccountIDIn(vs ...int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldIn(FieldRealAccountID, vs...))
}

// RealAccountIDNotIn applies the NotIn predicate on the "real_account_id" field.
func RealAccountIDNotIn(vs ...int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldNotIn(FieldRealAccountID, vs...))
}

// WebhookIDEQ applies the EQ predicate on the "webhook_id" field.
func WebhookIDEQ(v int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldEQ(FieldWebhookID, v))
}

// WebhookIDNEQ applies the NEQ predicate on the "webhook_id" field.
func WebhookIDNEQ(v int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldNEQ(FieldWebhookID, v))
}

// WebhookIDIn applies the In predicate on the "webhook_id" field.
func WebhookIDIn(vs ...int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldIn(FieldWebhookID, vs...))
}

// WebhookIDNotIn applies the NotIn predicate on the "webhook_id" field.
func WebhookIDNotIn(vs ...int64) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldNotIn(FieldWebhookID, vs...))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.FieldNEQ(FieldEnabled, v))
}

// HasRealAccount applies the HasEdge predicate on the "real_account" edge.
func HasRealAccount() predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RealAccountTable, RealAccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRealAccountWith applies the HasEdge predicate on the "real_account" edge with a given conditions (other predicates).
func HasRealAccountWith(preds ...predicate.RealAccount) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(func(s *sql.Selector) {
		step := newRealAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWebhook applies the HasEdge predicate on the "webhook" edge.
func HasWebhook() predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, WebhookTable, WebhookColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWebhookWith applies the HasEdge predicate on the "webhook" edge with a given conditions (other predicates).
func HasWebhookWith(preds ...predicate.UsageAlertWebhook) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(func(s *sql.Selector) {
		step := newWebhookStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageAlertBinding) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageAlertBinding) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageAlertBinding) predicate.UsageAlertBinding {
	return predicate.UsageAlertBinding(sql.NotPredicates(p))
}
